asakusafw/asakusafw

- docs/ja/source/_templates/layout.html
Caution: window.height function might depend on jQuery version.
> Make sidebar sticky when scrolling

- asakusa-parent/pom.xml
- dmdl-project/asakusa-dmdl-core/pom.xml
- legacy-project/asakusa-model-generator/pom.xml
- thundergate-project/asakusa-thundergate-dmdl/pom.xml
- utils-project/java-dom/pom.xml
- utils-project/javadoc-parser/pom.xml
Many pom.xml files have hard-coded JavaCC/JFlex versions.
> Put JavaCC/JFlex versions to the root pom.xml.

- yaess-project/asakusa-yaess-bootstrap/src/main/java/com/asakusafw/yaess/bootstrap/Yaess.java
This will fix FindBug `URF_UNREAD_FIELD` about `Yaess.Configuration.context`, it field is used for testing.
> Fix YAESS bootstrap for findbugs.

- README.md
Add links to repository of asakusafw subprojects.
> Revise README to add subprojects of asakusafw.

- hive-project/asakusa-hive-core/src/main/java/com/asakusafw/directio/hive/parquet/TimestampValueDrivers.java
To read/write bytes in little-endian, use `ByteBuffer.order(ByteOrder.LITTLE_ENDIAN)` instead of arranging byte order with bitwise operations.
> Use `ByteOrder.LITTLE_ENDIAN` to ser/de Parquet timestamp.

- docs/ja/source/windgate/user-guide.rst
Add a table describing correspondence among type of DMDL, Java and JDBC
> Add a table describing correspondence

- docs/ja/source/yaess/user-guide.rst
> Revise yaess document for new cli options.

- docs/ja/source/changelogs.rst
- docs/ja/source/product/target-platform.rst
- docs/ja/source/release-notes.rst
* Update release date
* Add changelog
* Change OS and JDK version on HDP
> Revise document for release 0.7.4.

- pom.xml
- yaess-project/asakusa-yaess-bootstrap/src/main/dist/yaess/bin/yaess-batch.sh
- yaess-project/asakusa-yaess-bootstrap/src/main/dist/yaess/bin/yaess-flow.sh
- yaess-project/asakusa-yaess-bootstrap/src/main/dist/yaess/bin/yaess-phase.sh
- yaess-project/asakusa-yaess-bootstrap/src/main/java/com/asakusafw/yaess/bootstrap/CommandLineUtil.java
- yaess-project/asakusa-yaess-bootstrap/src/main/java/com/asakusafw/yaess/bootstrap/Yaess.java
- yaess-project/asakusa-yaess-bootstrap/src/test/java/com/asakusafw/yaess/bootstrap/YaessTest.java
- yaess-project/asakusa-yaess-core/src/main/java/com/asakusafw/yaess/basic/BlobUtil.java
- yaess-project/asakusa-yaess-core/src/main/java/com/asakusafw/yaess/basic/FileBlob.java
- yaess-project/asakusa-yaess-core/src/main/java/com/asakusafw/yaess/basic/ProcessCommandScriptHandler.java
- yaess-project/asakusa-yaess-core/src/main/java/com/asakusafw/yaess/basic/ProcessExecutor.java
- yaess-project/asakusa-yaess-core/src/main/java/com/asakusafw/yaess/basic/ProcessHadoopScriptHandler.java
- yaess-project/asakusa-yaess-core/src/main/java/com/asakusafw/yaess/basic/ProcessUtil.java
- yaess-project/asakusa-yaess-core/src/main/java/com/asakusafw/yaess/core/Blob.java
- yaess-project/asakusa-yaess-core/src/main/java/com/asakusafw/yaess/core/CommandScript.java
- yaess-project/asakusa-yaess-core/src/main/java/com/asakusafw/yaess/core/ExecutionContext.java
- yaess-project/asakusa-yaess-core/src/main/java/com/asakusafw/yaess/core/ExecutionScript.java
- yaess-project/asakusa-yaess-core/src/main/java/com/asakusafw/yaess/core/FlowScript.java
- yaess-project/asakusa-yaess-core/src/main/java/com/asakusafw/yaess/core/HadoopScript.java
- yaess-project/asakusa-yaess-core/src/main/java/com/asakusafw/yaess/core/task/ExecutionTask.java
- yaess-project/asakusa-yaess-core/src/main/java/com/asakusafw/yaess/core/util/TemporaryFiles.java
- yaess-project/asakusa-yaess-core/src/test/java/com/asakusafw/yaess/basic/BasicCommandScriptHandlerTest.java
- yaess-project/asakusa-yaess-core/src/test/java/com/asakusafw/yaess/basic/FileBlobTest.java
- yaess-project/asakusa-yaess-core/src/test/resources/com/asakusafw/yaess/basic/blob.sh
- yaess-project/asakusa-yaess-jsch/src/main/java/com/asakusafw/yaess/jsch/JschProcessExecutor.java
- yaess-project/asakusa-yaess-jsch/src/main/resources/com/asakusafw/yaess/jsch/log.properties
- yaess-project/asakusa-yaess-jsch/src/test/java/com/asakusafw/yaess/jsch/JschProcessExecutorTest.java
- yaess-project/asakusa-yaess-jsch/src/test/java/com/asakusafw/yaess/jsch/SshCommandScriptHandlerTest.java
- yaess-project/asakusa-yaess-jsch/src/test/java/com/asakusafw/yaess/jsch/SshScriptHandlerTestRoot.java
- yaess-project/asakusa-yaess-jsch/src/test/resources/com/asakusafw/yaess/jsch/blob.sh
This enables to pass BLOB files to child tasks.
Usage:
```sh
.../yaess-batch.sh ... -E <extension-name>=</path/to/blob>
```
In the above, a local file `/path/to/blob` is passed to each
child task only if the task accepts an extension `extension-name`.
> Introduce extension mechanism to YAESS.

- yaess-project/asakusa-yaess-bootstrap/src/main/dist/yaess/bin/yaess-batch.sh
- yaess-project/asakusa-yaess-bootstrap/src/main/dist/yaess/bin/yaess-flow.sh
- yaess-project/asakusa-yaess-bootstrap/src/main/dist/yaess/bin/yaess-phase.sh
- yaess-project/asakusa-yaess-bootstrap/src/main/java/com/asakusafw/yaess/bootstrap/ArgumentList.java
- yaess-project/asakusa-yaess-bootstrap/src/main/java/com/asakusafw/yaess/bootstrap/CommandLineUtil.java
- yaess-project/asakusa-yaess-bootstrap/src/main/java/com/asakusafw/yaess/bootstrap/ExtendedArgument.java
- yaess-project/asakusa-yaess-bootstrap/src/main/java/com/asakusafw/yaess/bootstrap/Yaess.java
- yaess-project/asakusa-yaess-bootstrap/src/main/resources/com/asakusafw/yaess/bootstrap/log.properties
- yaess-project/asakusa-yaess-bootstrap/src/test/java/com/asakusafw/yaess/bootstrap/CommandLineUtilTest.java
- yaess-project/asakusa-yaess-bootstrap/src/test/java/com/asakusafw/yaess/bootstrap/ErroneousExtensionHandler.java
- yaess-project/asakusa-yaess-bootstrap/src/test/java/com/asakusafw/yaess/bootstrap/TestingExtensionHandler.java
- yaess-project/asakusa-yaess-bootstrap/src/test/java/com/asakusafw/yaess/bootstrap/YaessTest.java
- yaess-project/asakusa-yaess-bootstrap/src/test/resources/META-INF/services/com.asakusafw.yaess.core.ExtensionHandler
- yaess-project/asakusa-yaess-core/src/main/java/com/asakusafw/yaess/basic/BasicExtension.java
- yaess-project/asakusa-yaess-core/src/main/java/com/asakusafw/yaess/core/Extension.java
- yaess-project/asakusa-yaess-core/src/main/java/com/asakusafw/yaess/core/ExtensionHandler.java
- yaess-project/asakusa-yaess-core/src/test/java/com/asakusafw/yaess/basic/BasicExtensionTest.java
The previous CLI option `-E` is replaced with `-X-<name> <value>`.
> Introduce YAESS CLI extensions.

- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/value/StringOption.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/value/StringOptionUtil.java
- core-project/asakusa-runtime/src/test/java/com/asakusafw/runtime/value/StringOptionTest.java
- core-project/asakusa-runtime/src/test/java/com/asakusafw/runtime/value/StringOptionUtilTest.java
This commit includes the following APIs:
* `StringOption.modify(byte[], int, int)`
* `StringOptionUtility`
> Add utilities for StringOption.

- iterative-project/.gitignore
- iterative-project/asakusa-iterative-common/.gitignore
- iterative-project/asakusa-iterative-common/pom.xml
- iterative-project/asakusa-iterative-common/src/main/java/com/asakusafw/iterative/common/BaseCursor.java
- iterative-project/asakusa-iterative-common/src/main/java/com/asakusafw/iterative/common/IterativeExtensions.java
- iterative-project/asakusa-iterative-common/src/main/java/com/asakusafw/iterative/common/ParameterSet.java
- iterative-project/asakusa-iterative-common/src/main/java/com/asakusafw/iterative/common/ParameterTable.java
- iterative-project/asakusa-iterative-common/src/main/java/com/asakusafw/iterative/common/ParameterTableSerDe.java
- iterative-project/asakusa-iterative-common/src/main/java/com/asakusafw/iterative/common/basic/BasicParameterSet.java
- iterative-project/asakusa-iterative-common/src/main/java/com/asakusafw/iterative/common/basic/BasicParameterTable.java
- iterative-project/asakusa-iterative-common/src/main/java/com/asakusafw/iterative/common/basic/CursorUtil.java
- iterative-project/asakusa-iterative-common/src/main/java/com/asakusafw/iterative/common/basic/package-info.java
- iterative-project/asakusa-iterative-common/src/main/java/com/asakusafw/iterative/common/package-info.java
- iterative-project/asakusa-iterative-common/src/test/java/com/asakusafw/iterative/common/IterativeExtensionsTest.java
- iterative-project/asakusa-iterative-common/src/test/java/com/asakusafw/iterative/common/basic/BasicParameterSetTest.java
- iterative-project/asakusa-iterative-common/src/test/java/com/asakusafw/iterative/common/basic/BasicParameterTableTest.java
- iterative-project/asakusa-iterative-common/src/test/java/com/asakusafw/iterative/common/basic/CursorUtilTest.java
- iterative-project/asakusa-iterative-vocabulary/.gitignore
- iterative-project/asakusa-iterative-vocabulary/pom.xml
- iterative-project/asakusa-iterative-vocabulary/src/main/java/com/asakusafw/vocabulary/iterative/Iterative.java
- iterative-project/asakusa-iterative-vocabulary/src/main/java/com/asakusafw/vocabulary/iterative/IterativeBatch.java
- iterative-project/asakusa-iterative-vocabulary/src/main/java/com/asakusafw/vocabulary/iterative/package-info.java
- iterative-project/asakusa-iterative-yaess/.gitignore
- iterative-project/asakusa-iterative-yaess/pom.xml
- iterative-project/asakusa-iterative-yaess/src/main/java/com/asakusafw/yaess/iterative/ParameterTableHandler.java
- iterative-project/asakusa-iterative-yaess/src/main/java/com/asakusafw/yaess/iterative/package-info.java
- iterative-project/asakusa-iterative-yaess/src/main/resources/META-INF/services/com.asakusafw.yaess.core.ExtensionHandler
- iterative-project/asakusa-iterative-yaess/src/test/java/com/asakusafw/yaess/iterative/ParameterTableHandlerTest.java
- iterative-project/pom.xml
- pom.xml
These projects are ported from asakusafw-compiler repository.
(The original commit: asakusafw/asakusafw-compiler@28868d7d0e9d50749478e513b27e7339b63066b0)
> Add facilities for Iterative Extensions.

- docs/ja/source/contents.rst
- docs/ja/source/contribution.rst
* Adds contribution page to contents.
* Fixes rst format on contribution.rst
* Fix to show warning message in document build 
N/A
N/A
N/A
> Tiny fix on the contribution document

- docs/ja/source/application/gradle-plugin.rst
Fix typo on the gradle plugin document.
> Fix task name

- build-tools/src/main/resources/com/asakusafw/fb_exclude.xml
This commit removes FindBugs exclusion rules about asakuafw-legacy project.
see asakusafw/asakusafw-legacy#10.
N/A.
* asakusafw/asakusafw-legacy#10.
@akirakw
> Remove findbugs exclusion rules about downstream repositories.

- dmdl-project/asakusa-dmdl-core/src/main/javacc/DmdlParser.jj
A word 'projective' is missing in the comment of BNF for keyword.
Insert a word 'projective' in the comment to resolve missing.
N/A
N/A
ashigeru
> Insert a word "projective" in the comment

- docs/ja/source/application/yaess-log-visualization.rst
- docs/ja/source/yaess/jobqueue.rst
Revises documents to add attention to deprecated features.
N/A.
N/A.
asakusafw/asakusafw-sdk#98
N/A.
> Add deprecated attention to documents

- docs/ja/source/administration/configure-library-cache.rst
- docs/ja/source/directio/user-guide.rst
- docs/ja/source/directio/using-hive.rst
This PR removes document description for old version of EMR (AMI 2.x and 3.x).
N/A.
N/A.
N/A.
N/A.
> Remove description for old version of EMR

- docs/ja/source/application/gradle-plugin.rst
- docs/ja/source/introduction/start-guide.rst
This PR changes basic example project name on documents.
N/A.
N/A.
asakusafw/asakusafw-examples#21
N/A.
> Change basic example project name on documents

- docs/ja/source/_theme/asakusa/static/asakusa.css
This PR modifies sphinx documentation css to make attention block more noticeable.
N/A.
N/A.
N/A.
N/A.
> Modify attention directive block color

- README.md
- docs/README.md
- docs/ja/README
This PR add description about building document to README.
N/A.
N/A.
N/A.
N/A.
> Add description about building document to README

- docs/ja/source/application/gradle-plugin-reference.rst
- docs/ja/source/application/gradle-plugin.rst
This PR revises documentation about Gradle Plugin for using M3BP.
This PR also fixes some documentation bugs.
N/A.
N/A.
N/A.
N/A.
> Revise Gradle Plugin documentation for using M3BP

- docs/ja/source/application/gradle-plugin.rst
- docs/ja/source/product/target-platform.rst
This PR modifies target platform version on Sphinx documentation for release 0.8.1.
N/A.
N/A.
N/A.
N/A.
> Revise target platform document for version 0.8.1

- docs/ja/source/changelogs.rst
- docs/ja/source/conf.py
- docs/ja/source/release-notes.rst
This PR adds release notes for version 0.8.1
N/A.
N/A.
N/A.
N/A.
> Release notes for version 0.8.1

- docs/ja/source/changelogs.rst
- docs/ja/source/release-notes.rst
Update release date for version 0.8.1
> Update release date for version 0.8.1

- dsl-project/ashigel-compiler/src/main/java/com/asakusafw/compiler/flow/model/DataModelClassRepository.java
- dsl-project/ashigel-compiler/src/main/java/com/asakusafw/compiler/flow/packager/FilePackager.java
- dsl-project/ashigel-compiler/src/test/java/com/asakusafw/compiler/flow/packager/FilePackagerTest.java
- dsl-project/ashigel-compiler/src/test/java/com/asakusafw/compiler/operator/DelegateProcessor.java
- pom.xml
- utils-project/jsr199-testing/src/main/java/com/asakusafw/utils/java/jsr199/testing/VolatileCompiler.java
- utils-project/jsr199-testing/src/test/java/com/asakusafw/utils/java/jsr199/testing/MockProcessor.java
- utils-project/jsr269-bridge/src/test/java/com/asakusafw/utils/java/jsr269/bridge/DelegateProcessor.java
This PR bumps up Java version to 1.8.
N/A.
N/A.
N/A.
@akirakw
> Bump up Java version to 1.8.

- mapreduce/compiler/windgate/src/test/java/com/asakusafw/compiler/windgate/testing/jdbc/PairJdbcSupport.java
- mapreduce/compiler/windgate/src/test/java/com/asakusafw/compiler/windgate/testing/jdbc/SimpleJdbcSupport.java
- windgate-project/asakusa-windgate-core/src/main/java/com/asakusafw/windgate/core/vocabulary/DataModelJdbcSupport.java
- windgate-project/asakusa-windgate-core/src/main/java/com/asakusafw/windgate/core/vocabulary/JdbcProcess.java
- windgate-project/asakusa-windgate-dmdl/src/main/java/com/asakusafw/dmdl/windgate/jdbc/driver/JdbcSupportEmitter.java
- windgate-project/asakusa-windgate-dmdl/src/main/resources/com/asakusafw/dmdl/windgate/jdbc/driver/messages.properties
- windgate-project/asakusa-windgate-dmdl/src/test/java/com/asakusafw/dmdl/windgate/jdbc/driver/JdbcSupportEmitterTest.java
- windgate-project/asakusa-windgate-jdbc/src/main/java/com/asakusafw/windgate/jdbc/JdbcResourceUtil.java
- windgate-project/asakusa-windgate-jdbc/src/main/java/com/asakusafw/windgate/jdbc/JdbcScript.java
- windgate-project/asakusa-windgate-jdbc/src/test/java/com/asakusafw/windgate/jdbc/PairSupport.java
- windgate-project/asakusa-windgate-jdbc/src/test/java/com/asakusafw/windgate/jdbc/SupportWithPrivateConstructor.java
- windgate-project/asakusa-windgate-jdbc/src/test/java/com/asakusafw/windgate/jdbc/VoidSupport.java
- windgate-project/asakusa-windgate-vocabulary/src/main/java/com/asakusafw/vocabulary/windgate/JdbcDescriptionUtil.java
- windgate-project/asakusa-windgate-vocabulary/src/main/java/com/asakusafw/vocabulary/windgate/JdbcExporterDescription.java
- windgate-project/asakusa-windgate-vocabulary/src/main/java/com/asakusafw/vocabulary/windgate/JdbcImporterDescription.java
- windgate-project/asakusa-windgate-vocabulary/src/main/resources/com/asakusafw/vocabulary/windgate/messages.properties
- windgate-project/asakusa-windgate-vocabulary/src/test/java/com/asakusafw/vocabulary/windgate/JdbcExporterDescriptionTest.java
- windgate-project/asakusa-windgate-vocabulary/src/test/java/com/asakusafw/vocabulary/windgate/JdbcImporterDescriptionTest.java
- windgate-project/asakusa-windgate-vocabulary/src/test/java/com/asakusafw/vocabulary/windgate/MockJdbcSupport.java
This PR introduces some properties into WindGate JDBC vocabularies.
N/A.
This introduces the following features.
* `JdbcSupport.getColumnMap()`
* mappings between each table column and data model property for custom JDBC operations
* `Jdbc{Importer,Exporter}Description.getOptions()`
* the extra options for WindGate JDBC operations
N/A.
@akirakw
> Add more details to WindGate JDBC vocabularies.

- windgate-project/asakusa-windgate-core/src/main/java/com/asakusafw/windgate/core/vocabulary/JdbcProcess.java
- windgate-project/asakusa-windgate-jdbc/src/main/java/com/asakusafw/windgate/jdbc/JdbcDrainDriver.java
- windgate-project/asakusa-windgate-jdbc/src/main/java/com/asakusafw/windgate/jdbc/JdbcProfile.java
- windgate-project/asakusa-windgate-jdbc/src/test/java/com/asakusafw/windgate/jdbc/JdbcDrainDriverTest.java
- windgate-project/asakusa-windgate-jdbc/src/test/java/com/asakusafw/windgate/jdbc/JdbcProfileTest.java
- windgate-project/asakusa-windgate-vocabulary/src/main/java/com/asakusafw/vocabulary/windgate/JdbcDescriptionUtil.java
- windgate-project/asakusa-windgate-vocabulary/src/main/java/com/asakusafw/vocabulary/windgate/JdbcExporterDescription.java
- windgate-project/asakusa-windgate-vocabulary/src/main/java/com/asakusafw/vocabulary/windgate/JdbcImporterDescription.java
- windgate-project/asakusa-windgate-vocabulary/src/test/java/com/asakusafw/vocabulary/windgate/JdbcExporterDescriptionTest.java
- windgate-project/asakusa-windgate-vocabulary/src/test/java/com/asakusafw/vocabulary/windgate/JdbcImporterDescriptionTest.java
This PR introduces a simple extension point mechanism to WindGate JDBC which enables fast-path access to individual RDBMS.
The latest implementation of WindGate JDBC uses only standard SQL, basic `SELECT` and `INSERT` statements exchange datasets between RDBMS and batch applications. This feature will improve their performance by using non-standard data access via extension points.
To enable extensions, batch application must satisfy the all following conditions:
* (1) put a symbol which represents such the optimization into the related `Jdbc{Importer, Exporter}Description.getOptions()`
* (2) put the symbol into the related WindGate profile script as `resource.jdbc.optimizations`
* (3) the runtime engine (a.k.a. WindGate JDBC) supports such the optimization
This PR also includes an …
> Introduce extension points to WindGate JDBC runtime.

- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/TestExecutionPlan.java
- testing-project/asakusa-test-inprocess/src/main/java/com/asakusafw/testdriver/inprocess/InProcessJobExecutor.java
This PR revises log messages around test driver features.
The latest implementation, test driver shows the environment variables in the console each in-process tasks.
N/A.
N/A.
@akirakw
> Revise log messages around test driver features.

- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/stage/launcher/Util.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/util/hadoop/ConfigurationProvider.java
- dmdl-project/asakusa-dmdl-core/src/main/java/com/asakusafw/dmdl/analyzer/DmdlAnalyzer.java
- dmdl-project/asakusa-dmdl-core/src/main/java/com/asakusafw/dmdl/source/DmdlSourceDirectory.java
- hive-project/asakusa-hive-cli/src/main/java/com/asakusafw/directio/hive/tools/cli/ClassCollector.java
- mapreduce/compiler/core/src/main/java/com/asakusafw/compiler/batch/processor/DependencyLibrariesProcessor.java
- mapreduce/compiler/core/src/main/java/com/asakusafw/compiler/common/FileRepository.java
- mapreduce/compiler/core/src/main/java/com/asakusafw/compiler/flow/packager/FilePackager.java
- mapreduce/compiler/core/src/main/java/com/asakusafw/compiler/testing/DirectBatchCompiler.java
- mapreduce/compiler/core/src/main/java/com/asakusafw/compiler/testing/DirectFlowCompiler.java
- pom.xml
- testing-project/asakusa-test-compiler/src/main/java/com/asakusafw/testdriver/compiler/util/DeploymentUtil.java
- testing-project/asakusa-test-data-generator/src/main/java/com/asakusafw/testdata/generator/excel/SheetEditor.java
- testing-project/asakusa-test-data-generator/src/main/java/com/asakusafw/testdata/generator/excel/WorkbookInfo.java
- testing-project/asakusa-test-data-generator/src/test/java/com/asakusafw/testdata/generator/excel/ExcelTesterRoot.java
- testing-project/asakusa-test-data-provider/src/main/java/com/asakusafw/testdriver/excel/DefaultExcelRuleExtractor.java
- testing-project/asakusa-test-data-provider/src/main/java/com/asakusafw/testdriver/excel/ExcelDataDriver.java
- testing-project/asakusa-test-data-provider/src/main/java/com/asakusafw/testdriver/excel/ExcelSheetDataModelSource.java
- testing-project/asakusa-test-data-provider/src/main/java/com/asakusafw/testdriver/excel/WorkbookInfo.java
- testing-project/asakusa-test-data-provider/src/main/java/com/asakusafw/testdriver/excel/legacy/LegacyExcelRuleExtractor.java
- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/TestDriverContext.java
- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/Util.java
- testing-project/asakusa-test-inprocess/src/main/java/com/asakusafw/testdriver/inprocess/EmulatorUtils.java
- windgate-project/asakusa-windgate-core/src/main/java/com/asakusafw/windgate/file/session/FileSessionProvider.java
- windgate-project/asakusa-windgate-test-inprocess/src/main/java/com/asakusafw/testdriver/windgate/emulation/AbstractWindGateCommandEmulator.java
- windgate-project/asakusa-windgate-test-moderator/src/main/java/com/asakusafw/testdriver/windgate/WindGateTestHelper.java
- windgate-project/asakusa-windgate-test-moderator/src/test/java/com/asakusafw/testdriver/windgate/JdbcDriverCleanerTest.java
This PR bumps up artifact versions dependencies and Maven plug-ins.
N/A.
We also revises code style for:
* FindBugs `3.0.{0->4}`
* Apache POI `3.{13->15}`
N/A.
@akirakw
> Bump up dependency versions.

- NOTICE
This PR updates license year to 2017 in NOTICE. 
(follow up #709)
N/A.
N/A.
N/A.
N/A.
> License year updated to 2017

- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/io/text/FieldReader.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/io/text/TextFormat.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/io/text/TextFormatException.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/io/text/UnmappableOutput.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/io/text/delimited/DelimitedFieldWriter.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/io/text/delimited/DelimitedTextFormat.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/io/text/driver/InputDriver.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/io/text/driver/OutputDriver.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/io/text/driver/StandardFieldOutputOption.java
- core-project/asakusa-runtime/src/test/java/com/asakusafw/runtime/io/text/delimited/DelimitedFieldWriterTest.java
- core-project/asakusa-runtime/src/test/java/com/asakusafw/runtime/io/text/directio/AbstractTextStreamFormatTest.java
- core-project/asakusa-runtime/src/test/java/com/asakusafw/runtime/io/text/driver/OutputDriverTest.java
- directio-project/asakusa-directio-dmdl/src/main/java/com/asakusafw/dmdl/directio/text/AbstractTextStreamFormatGenerator.java
This PR is minor revision of #713.
N/A.
N/A.
* #713
N/A.
> Revise Direct I/O delimited text.

- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/DriverElementBase.java
This PR fixes exception message on `DriverElementBase` ( follow up #701 ).
N/A.
N/A.
#701
> Fix exception message on DriverElementBase

- dmdl-project/asakusa-dmdl-core/src/main/resources/com/asakusafw/dmdl/parser/SyntaxErrorKind.properties
Dat grammar natura
Let's be native
> More natural English

- integration/src/integration-test/java/com/asakusafw/integration/core/AsakusaOrganizerTest.java
- integration/src/integration-test/java/com/asakusafw/integration/core/AsakusaProjectTest.java
- integration/src/integration-test/java/com/asakusafw/integration/core/OperationToolsTest.java
- integration/src/main/java/com/asakusafw/integration/AsakusaConstants.java
This PR provides the command name constants which are widely appeared in other integration tests.
N/A.
N/A.
N/A.
> Refactor command names in integration test.

- gradle/src/main/groovy/com/asakusafw/gradle/tasks/internal/AbstractTestToolTask.groovy
This PR fixes Gradle `runTest` command for Windows.
Gradle `runTest` task sometimes generates too long command line for Windows platform. This PR shortens the command line by using tool launcher, which accepts command line file and then delegates another main class with the restored command line.
N/A.
* asakusafw/asakusafw-compiler#158
> TestToolTask should launch java via tool launcher.

- operation-project/command-portal/src/main/dist/bin/asakusa
- operation-project/command-portal/src/main/dist/bin/asakusa.cmd
- operation-project/command-portal/src/main/java/com/asakusafw/operation/tools/portal/AsakusaPortal.java
- operation-project/command-portal/src/main/java/com/asakusafw/operation/tools/portal/SimpleLoggerUtil.java
- utils-project/gradle-launcher/src/main/java/com/asakusafw/utils/gradle/BasicCommandLauncher.java
- workflow/cli/src/main/java/com/asakusafw/workflow/cli/common/ExecutionContextParameter.java
- workflow/cli/src/main/java/com/asakusafw/workflow/cli/common/WorkflowParameter.java
- workflow/executor/src/main/java/com/asakusafw/workflow/executor/basic/BasicBatchExecutor.java
- workflow/executor/src/main/java/com/asakusafw/workflow/executor/basic/BasicCommandLauncher.java
- workflow/executor/src/main/java/com/asakusafw/workflow/executor/basic/BasicDeleteTaskExecutor.java
- workflow/executor/src/main/java/com/asakusafw/workflow/executor/basic/BasicJobflowExecutor.java
- workflow/model/src/main/java/com/asakusafw/workflow/model/basic/BasicCommandTaskInfo.java
- workflow/model/src/main/java/com/asakusafw/workflow/model/basic/BasicDeleteTaskInfo.java
- workflow/model/src/main/java/com/asakusafw/workflow/model/basic/BasicHadoopTaskInfo.java
This PR revises messages of `asakusa run`.
N/A.
N/A.
* #750
* #752
> Revise messages of `asakusa run`.

- .mvn/wrapper/maven-wrapper.properties
- build-tools/src/main/resources/com/asakusafw/checkstyle.xml
- pom.xml
This PR bumps Maven version defines Maven Wrapper.
This PR also bumps some Maven plugin version.
This also changes some checkstyle rules for upgrading checkstyle version.
N/A.
N/A.
N/A.
> Bump up Maven Wrapper and Maven Plugins

- gradle/build.gradle
- integration/build.gradle
- pom.xml
This PR bumps up dependency library versions.
N/A.
N/A.
N/A.
> Bump up dependency library versions

- pom.xml
This PR bumps up Hive library versions.
N/A.
N/A.
N/A.
> Bump Hive version

- gradle/gradle/wrapper/gradle-wrapper.properties
- gradle/src/main/resources/META-INF/asakusa-gradle/defaults.properties
- gradle/src/test/groovy/com/asakusafw/gradle/plugins/AsakusaUpgradeTest.groovy
- integration/gradle/wrapper/gradle-wrapper.properties
- pom.xml
This PR bump up the Gradle version to 4.2
N/A.
N/A.
N/A.
> Bump Gradle version to 4.2

- integration/src/integration-test/java/com/asakusafw/integration/core/OperationToolsTest.java
- operation-project/command-portal/src/main/java/com/asakusafw/operation/tools/portal/AsakusaPortal.java
- operation-project/command-portal/src/main/java/com/asakusafw/operation/tools/portal/VersionCommand.java
This PR adds `asakusa version` command. It displays running version of Asakusa Framework.
N/A.
N/A.
* #750
> Add `asakusa version` command.

- operation-project/command-portal/src/main/java/com/asakusafw/operation/tools/portal/VersionCommand.java
This PR enables `asakusa version` to show current Hadoop command location.
N/A.
N/A.
* #782
> Revise `asakusa version` to show hadoop command location.

- operation-project/directio/src/main/java/com/asakusafw/operation/tools/directio/file/FileDeleteCommand.java
- operation-project/directio/src/main/java/com/asakusafw/operation/tools/directio/file/FileListCommand.java
This PR fixes command argument descriptions of `directio {list, delete}`.
N/A.
N/A.
* #765
> Revise argument description of `directio {list,delete}`.

- operator/core/src/main/java/com/asakusafw/operator/flowpart/FlowPartAnalyzer.java
This PR enables to avoid errors if a flow-part class has `@{Import, Export}` annotations in its constructor parameters.
The new operator DSL compiler (`./operator`) raises errors if flow-parts have `@{Import, Export}` annotations even if the legacy compiler does not. This PR replace them with warning messages, and continues the processing.
Note that, you can suppress the above warning messages by putting the following line into you `build.gradle`.
```gradle
asakusafw.javac.processorOption `com.asakusafw.operator.warning`, `IGNORE`
```
* options of `com.asakusafw.operator.warning`:
* `IGNORE` - suppress warning messages
* `REPORT` - show warning messages
* `FAIL` - show error messages and stop compilation, like as `<= 0.10.0`
N/A.
> Avoid errors if flow-part has import/export annotations.

- dmdl-project/asakusa-dmdl-core/src/main/java/com/asakusafw/dmdl/analyzer/driver/AutoProjectionDriver.java
- dmdl-project/asakusa-dmdl-core/src/test/java/com/asakusafw/dmdl/analyzer/driver/AutoProjectionDriverTest.java
This PR fixes `@auto_projection` for #816.
SInce #816, `@auto_projection` does not work correct.
N/A.
* #816
> Fix auto_projection.

- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/OperatorTestEnvironment.java
- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/OperatorTestEnvironmentTest.java
This PR introduces `OperatorTestEnvironment.dump()` method which stores test data into files as Direct I/O formats, like `*Tester.dumpActual()`.
N/A.
N/A.
N/A.
> Add `OperatorTestEnvironment.dump()`.

- pom.xml
This PR bumps up Jackson to the latest version.
N/A.
N/A.
N/A.
> Bump up Jackson version

- hive-project/asakusa-hive-core/src/main/java/com/asakusafw/directio/hive/orc/AbstractOrcFileFormat.java
- hive-project/asakusa-hive-core/src/main/java/com/asakusafw/directio/hive/orc/OrcFileInput.java
- hive-project/asakusa-hive-core/src/main/java/com/asakusafw/directio/hive/orc/OrcFileOutput.java
- hive-project/asakusa-hive-core/src/main/java/com/asakusafw/directio/hive/orc/Util.java
- hive-project/asakusa-hive-core/src/main/java/com/asakusafw/directio/hive/parquet/ParquetFileInput.java
- hive-project/asakusa-hive-core/src/main/java/com/asakusafw/directio/hive/parquet/ParquetFileOutput.java
- hive-project/asakusa-hive-core/src/main/java/com/asakusafw/directio/hive/parquet/Util.java
This PR fixes computing Direct I/O Hive (Orc/Parquet) read/written file size.
N/A.
N/A.
N/A.
> better tracking Orc/Parquet file size.

- pom.xml
This PR bumps up `snappy-java` to latest version.
N/A.
N/A.
N/A.
> Bump snappy-java version

- workflow/.gitignore
This PR adds .gitignore for using VSCode and for workflow module.
N/A.
N/A.
N/A.
> Add .gitignore
