asakusafw/asakusafw

- asakusa-parent/pom.xml
`codehaus.org` has been superseded.
> Remove codehaus.org repositories.

- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/core/Report.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/report/CommonsLoggingReport.java
- core-project/asakusa-runtime/src/test/java/com/asakusafw/runtime/core/ReportTest.java
- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/OperatorTestEnvironmentTest.java
The Report API is also used in other execution environments, like as [Asakusa on Spark](https://github.com/asakusafw/asakusafw-spark). This improvement will simplify to use the API from such environments.
Note that this breaks source compatibility of Report API **implementations** (not application code).
> Make methods in Report.Delegate public.

- windgate-project/asakusa-windgate-bootstrap/src/test/java/com/asakusafw/windgate/bootstrap/CommandLineUtilTest.java
On Mac OS X, the temporary directory location is in `/var/folders/..`,
but its canonical path is `/private/var/folders/..`.
> Fix a test case for Mac OS X.

- dsl-project/ashigel-compiler/src/test/java/com/asakusafw/compiler/util/tester/HadoopDriver.java
Developers can set `-Dhadoop.builtin=false` to use an installed
Hadoop command (`$HADOOP_CMD`) instead of the built-in engine.
> Make `-Dhadoop.builtin` default enabled on building framework.

- yaess-project/asakusa-yaess-core/src/main/java/com/asakusafw/yaess/basic/ProcessUtil.java
- yaess-project/asakusa-yaess-core/src/main/java/com/asakusafw/yaess/core/ExecutionScriptHandler.java
- yaess-project/asakusa-yaess-core/src/test/resources/com/asakusafw/yaess/basic/arguments.sh
- yaess-project/asakusa-yaess-core/src/test/resources/com/asakusafw/yaess/basic/blob.sh
- yaess-project/asakusa-yaess-jsch/src/main/java/com/asakusafw/yaess/jsch/JschProcessExecutor.java
- yaess-project/asakusa-yaess-jsch/src/test/resources/com/asakusafw/yaess/jsch/arguments.sh
- yaess-project/asakusa-yaess-jsch/src/test/resources/com/asakusafw/yaess/jsch/blob.sh
In #546, YAESS passes extensions via extra command arguments.
From this commit, YAESS will pass it via environment variables
named `ASAKUSA_EXTENSION_<name>`, and no extra arguments will be
passed.
For example, `yaess-batch.sh ... -E hoge=/path/to/extension` will
pass the extension file contents via `ASAKUSA_EXTENSION_hoge`
(only if each task accepts the `hoge` extension).
> YAESS extensions should be passed via environment vars instead.

- core-project/asakusa-runtime-all/pom.xml
- core-project/asakusa-runtime-workaround/.gitignore
- core-project/asakusa-runtime-workaround/pom.xml
- core-project/asakusa-runtime-workaround/src/main/java/com/asakusafw/runtime/workaround/RuntimeWorkaround.java
- core-project/asakusa-runtime-workaround/src/main/java/com/asakusafw/runtime/workaround/package-info.java
- core-project/asakusa-runtime-workaround/src/main/java/com/asakusafw/runtime/workaround/snappyjava/MacSnappyJavaWorkaround.java
- core-project/asakusa-runtime-workaround/src/main/java/com/asakusafw/runtime/workaround/snappyjava/package-info.java
- core-project/asakusa-runtime-workaround/src/main/resources/META-INF/services/com.asakusafw.runtime.stage.StageConfigurator
- core-project/pom.xml
- testing-project/asakusa-test-driver/pom.xml
- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/configurator/SnappyConfigurator.java
- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/TesterTestRoot.java
Some Hadoop distributions contain old versions of `snappy-java`, and they don't work well on Mac with JDK7+. This workaround will fix its problem.
Hadoop configurations:
`com.asakusafw.workaround.snappyjava.enabled`
whether the feature is enabled or not (default: `true`)
`com.asakusafw.workaround.snappyjava.skipOnUnknown`
whether skip unrecognized versions or not (default: `true`)
> Add workaround for old snappy-java on Mac.

- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/stage/output/TemporaryOutputFormat.java
Hadoop property:
`com.asakusafw.temporary.output`
output name prefix (default: `part`)
> Make TemporaryOutputFormat file name configurable.

- docs/ja/source/application/gradle-plugin-reference.rst
- docs/ja/source/application/gradle-plugin-v08-changes.rst
Fix typo "行なわた" -> "行われた".  
Trailing spaces also deleted with ATOM default setting. ( It cause nothing but make more diffs than I thought.)
> Fix Japanese Typo

- .gitignore
`.idea` and `*.iml` is automatically-generated files by IntelliJ, which floods the result of `git status`.
> Add IntelliJ-generated files to .gitignore

- build-tools/pom.xml
Add licene-maven-plugin pom definition to build-tools
Fix fail to run `mvn license:check` on asakusafw root directory
because of missing licene-maven-plugin definition to  pom.xml on build-tools project.
N/A.
N/A.
N/A.
> Add licene-maven pom definition to build-tools

- sdk-project/asakusa-sdk-app-hive/.gitignore
- sdk-project/asakusa-sdk-app-hive/pom.xml
- sdk-project/asakusa-sdk-hive/pom.xml
- sdk-project/pom.xml
This PR adds `com.asakusafw:asakusa-hive-plugin`  ( see: #625 ) to `asakusafw-sdk-hive`
Executes Hive schema info generator at MapReduce DSL Compile ( ex. run at `mapreduceCompileBatchapps` )
N/A.
#625
N/A.
> Add Hive schema info generator to Hive SDK artifact

- dmdl-project/asakusa-dmdl-core/src/main/javacc/DmdlParser.jj
The region name for the AttributeElement rule should be "attribute-element."
Change the region name for the AttributeElement rule from "attribute-element-list" to "attribute-element."
N/A
N/A
ashigeru
> Fix the region name

- windgate-project/asakusa-windgate-core/src/main/java/com/asakusafw/windgate/core/GateProfile.java
- windgate-project/asakusa-windgate-core/src/main/java/com/asakusafw/windgate/core/util/VoidDrainDriver.java
- windgate-project/asakusa-windgate-core/src/main/java/com/asakusafw/windgate/core/util/VoidResourceProvider.java
- windgate-project/asakusa-windgate-core/src/main/java/com/asakusafw/windgate/core/util/VoidSourceDriver.java
- windgate-project/asakusa-windgate-vocabulary/src/main/java/com/asakusafw/vocabulary/windgate/Constants.java
This commit introduces `void` resource into WindGate.
Current `hadoop` resource always requires one or more input paths to execute data transferring. But in some situations, only resource initialization operation is required without any inputs. For example, some optimization will remove all upstream sources to WindGate outputs (asakusafw/asakusafw-compiler#54).
This commit introduces `void` resource, and it is automatically enabled even if it is explicitly declared in each WindGate profile file.
* asakusafw/asakusafw-compiler#54
@akirakw
> Introduce VOID resource to WindGate.

- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/directio/DirectDataSource.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/directio/hadoop/HadoopDataSource.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/directio/hadoop/HadoopDataSourceCore.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/directio/keepalive/KeepAliveDataSource.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/stage/input/BridgeInputFormat.java
- core-project/asakusa-runtime/src/test/java/com/asakusafw/runtime/directio/MockDirectDataSource.java
- core-project/asakusa-runtime/src/test/java/com/asakusafw/runtime/directio/keepalive/KeepAliveDataSourceTest.java
This PR revises error messages when Direct I/O input does not exist.
The latest implementation only shows the base path and resource pattern of missed resources, like
> java.io.IOException: Input not found (datasource=root, **basePath="master"**, **resourcePattern="store_info.csv"**, type=com.example.modelgen.dmdl.model.StoreInfo)
The new implementation will show the *resolved path* on the target datastore instead, like:
> java.io.IOException: Input not found (datasource=root, **path="file:/.../target/testing/directio/master/store_info.csv"**, type=com.example.modelgen.dmdl.model.StoreInfo)
This PR introduces a new method `DirectDataSource.path()` to resolve a pair of base path and resource pattern into a path on its datastore.
Note that, this revision is only for Asakusa on MapReduce. We …
> Revise error message on Direct I/O input missing.

- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/core/util/Shared.java
- core-project/asakusa-runtime/src/test/java/com/asakusafw/runtime/core/util/SharedTest.java
This PR may improve performance of `Shared.get()`.
In the latest implementation, `Shared.get()` always enters the object monitor. This PR reduces `synchronized` scope and use `AtomicReference` to provide the shared value outside the `synchronized`.
N/A.
N/A.
@shino
> Reduce synchronized scope in `Shared.get()`.

- docs/ja/source/conf.py
This PR fixes to document build warning on Sphinx 1.4.
Sphinx extention `sphinx.ext.pngmath` has been deprecated and should use `sphinx.ext.imgmath` instead.
N/A.
N/A.
N/A.
> Fix document build warning on Sphinx 1.4

- docs/ja/source/directio/csv-format.rst
- docs/ja/source/directio/sequencefile-format.rst
- docs/ja/source/directio/using-hive.rst
- docs/ja/source/dmdl/start-guide.rst
- docs/ja/source/dmdl/user-guide.rst
- docs/ja/source/sandbox/directio-line.rst
- docs/ja/source/sandbox/directio-tsv.rst
- docs/ja/source/sandbox/windgate-tsv.rst
- docs/ja/source/windgate/start-guide.rst
- docs/ja/source/windgate/user-guide.rst
This PR add DMDL script syntax highlighting on sphinx documentation using [pygments-dmdl](https://pypi.python.org/pypi/pygments-dmdl).
(very thanks to @cocoatomo for creating excellent product!)
N/A.
N/A.
N/A.
N/A.
> Add syntax highlight to DMDL using pygments-dmdl

- docs/ja/source/application/gradle-plugin.rst
- docs/ja/source/product/target-platform.rst
This PR modifies Gradle version to 2.14.1 on documents.
See as follows:
- asakusafw/asakusafw-sdk#100
- asakusafw/asakusafw-spark#198
- asakusafw/asakusafw-m3bp#72
N/A.
- asakusafw/asakusafw-sdk#100
- asakusafw/asakusafw-spark#198
- asakusafw/asakusafw-m3bp#72
N/A
> Bump Gradle version to 2.14.1 on documents

- docs/ja/source/conf.py
- docs/ja/source/index.rst
- docs/ja/source/introduction/start-guide.rst
- docs/ja/source/release-notes.rst
This PR modifies Sphinx documentation for adding document link to [Asakusa Framework Tutorial](https://github.com/asakusafw/asakusafw-basic-tutorial).
N/A.
N/A.
N/A.
N/A.
> Add document link to basic tutorial

- hive-project/asakusa-hive-info/src/main/java/com/asakusafw/directio/hive/info/MapType.java
This PR removes `WIP` version in Javadoc.
#624 includes `@since WIP` tag.
N/A.
* #624
N/A.
> Remove `WIP` version in Javadoc.

- iterative-project/asakusa-iterative-vocabulary/src/main/java/com/asakusafw/vocabulary/iterative/Iterative.java
- pom.xml
This PR add pom profile for disabling DocLint missing option (sometimes this option is too strict) .
N/A.
N/A.
N/A.
N/A.
> Add profile to disable DocLint missing option

- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/directio/Counter.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/directio/hadoop/HadoopDataSourceCore.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/directio/hadoop/HadoopDataSourceProfile.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/directio/hadoop/HadoopDataSourceUtil.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/stage/directio/AbstractNoReduceDirectOutputMapper.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/stage/directio/DirectOutputReducer.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/stage/output/BridgeOutputFormat.java
- core-project/asakusa-runtime/src/test/java/com/asakusafw/runtime/directio/hadoop/HadoopDataSourceProfileTest.java
- core-project/asakusa-runtime/src/test/java/com/asakusafw/runtime/directio/hadoop/HadoopDataSourceUtilTest.java
This PR enables to move staged files into committed area in parallel.
Direct I/O has a simple transactional output mechanism. It first rolls up uncommitted files into "staging area", and then moves the files into "committed area" in roll-forward operation.
In the latest implementation, the roll-forward operation moves files one by one. It sometimes takes long time if there are too many files or move operations are much slow.
To put a new Direct I/O configuration to `asakusa-resources.xml`, each roll-forward operation will run in parallel.
* `com.asakusafw.directio.<ID>.threads.commit=<N>`
* max number of threads for moving files in roll-forward operation
* default: `1` (single-threaded)
N/A.
@akirakw
> Enable Direct I/O parallel roll-forward.

- testing-project/asakusa-test-data-provider/src/main/java/com/asakusafw/testdriver/excel/ExcelSheetRuleProvider.java
- testing-project/asakusa-test-data-provider/src/test/java/com/asakusafw/testdriver/excel/ExcelSheetRuleProviderTest.java
- testing-project/asakusa-test-moderator/src/main/java/com/asakusafw/testdriver/core/VerifyRule.java
This PR fixes "do not verify `[-]`" behavior in Excel test rule sheets.
The latest implementation, "do not verify `[-]`" ignores key properties. This may occur error when there are two or more expected/actual data.
We added a special rule for "do not verify `[-]`" that accepts any inputs.
N/A.
@akirakw
> Fix "do not verify" behavior in Excel sheets.

- windgate-project/asakusa-windgate-core/src/main/java/com/asakusafw/windgate/core/ParameterList.java
- windgate-project/asakusa-windgate-core/src/test/java/com/asakusafw/windgate/core/ParameterListTest.java
This PR enables default values of variables (`${variable}`) in WindGate profiles.
The latest implementation, WindGate will raise error if the environment variable in the profile script is not defined.
This is similar to #491, but this is for WindGate.
A placeholder `${name-default}` will be resolved as like `${name}` if the environment variable `name` is defined, or `default` if it is not defined.
* #491
@akirakw
> Support default value of variables in WindGate profiles.

- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/io/csv/CsvConfiguration.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/io/csv/CsvEmitter.java
- core-project/asakusa-runtime/src/test/java/com/asakusafw/runtime/io/csv/CsvEmitterTest.java
- directio-project/asakusa-directio-dmdl/src/main/java/com/asakusafw/dmdl/directio/csv/driver/CsvFieldDriver.java
- directio-project/asakusa-directio-dmdl/src/main/java/com/asakusafw/dmdl/directio/csv/driver/CsvFieldTrait.java
- directio-project/asakusa-directio-dmdl/src/main/java/com/asakusafw/dmdl/directio/csv/driver/CsvFormatEmitter.java
- directio-project/asakusa-directio-dmdl/src/test/java/com/asakusafw/dmdl/directio/csv/driver/CsvFormatEmitterTest.java
- directio-project/asakusa-directio-dmdl/src/test/resources/com/asakusafw/dmdl/directio/csv/driver/quote.txt
- windgate-project/asakusa-windgate-dmdl/src/main/java/com/asakusafw/dmdl/windgate/csv/driver/CsvFieldDriver.java
- windgate-project/asakusa-windgate-dmdl/src/main/java/com/asakusafw/dmdl/windgate/csv/driver/CsvFieldTrait.java
- windgate-project/asakusa-windgate-dmdl/src/main/java/com/asakusafw/dmdl/windgate/csv/driver/CsvSupportEmitter.java
- windgate-project/asakusa-windgate-dmdl/src/test/java/com/asakusafw/dmdl/windgate/csv/driver/CsvSupportEmitterTest.java
- windgate-project/asakusa-windgate-dmdl/src/test/resources/com/asakusafw/dmdl/windgate/csv/driver/quote.txt
This PR enables to configure field quoting strategy of CSV outputs.
The latest implementation, Direct I/O and WindGate CSV outputs quote fields only if the field value contain meta-characters (`"`, `,`, ...), but some CSV parsers only accepts quoted fields even if it is redundant.
The attribute element named `quote` is now enabled to `@directio.csv.field` (Direct I/O) and `@windgate.csv.field` (WindGate). The default behavior of both is as the conventional quoting strategy. 
* `@directio.csv.field(quote="default|needed|always")`
* configures quoting mode:
* `default` - as `needed`
* `needed` - quote only if needed
* `always` - always quote
* default: `default`
* `@windgate.csv.field(quote="default|needed|always")`
* configures quoting mode:
* `default` - as `needed`
* `needed` - quote …
> Add force quote mode for CSV outputs.

- windgate-project/asakusa-windgate-vocabulary/src/main/java/com/asakusafw/vocabulary/windgate/JdbcAttribute.java
- windgate-project/asakusa-windgate-vocabulary/src/main/java/com/asakusafw/vocabulary/windgate/JdbcDescriptionUtil.java
- windgate-project/asakusa-windgate-vocabulary/src/main/java/com/asakusafw/vocabulary/windgate/JdbcExporterDescription.java
- windgate-project/asakusa-windgate-vocabulary/src/main/java/com/asakusafw/vocabulary/windgate/JdbcImporterDescription.java
- windgate-project/asakusa-windgate-vocabulary/src/main/resources/com/asakusafw/vocabulary/windgate/messages.properties
- windgate-project/asakusa-windgate-vocabulary/src/test/java/com/asakusafw/vocabulary/windgate/JdbcExporterDescriptionTest.java
- windgate-project/asakusa-windgate-vocabulary/src/test/java/com/asakusafw/vocabulary/windgate/JdbcImporterDescriptionTest.java
This PR improves API robustness of #671.
In #671, we introduced typed options into JDBC importer/exporter descriptions, but the options has less flexibility because it is declared as `enum`.
This PR introduces `JdbcAttribute` interface as a super type of the options. It may reduce DSL strictness but will help future extensions.
* #671
@akirakw
> Make WindGate JDBC options API more robust.

- windgate-project/asakusa-windgate-hadoopfs/src/main/java/com/asakusafw/windgate/hadoopfs/ssh/WindGateHadoopGet.java
- windgate-project/asakusa-windgate-hadoopfs/src/main/java/com/asakusafw/windgate/hadoopfs/temporary/FileSystemModelInputProvider.java
- windgate-project/asakusa-windgate-hadoopfs/src/main/resources/com/asakusafw/windgate/hadoopfs/log.properties
- windgate-project/asakusa-windgate-hadoopfs/src/test/java/com/asakusafw/windgate/hadoopfs/ssh/WindGateHadoopGetTest.java
This PR suppresses errors on WindGate exporter when the output files were not generated.
The latest implementation raises errors if input files of WindGate exporter, which generated by execution engine like MapReduce, Spark, or M3BP, even if there are no data to export (empty files are required).
This PR enables to raise warning logs if there are no input files without errors.
N/A.
@akirakw
> Suppress WindGate exporter errors even if there are no result files.

- windgate-project/asakusa-windgate-dmdl/src/main/java/com/asakusafw/dmdl/windgate/jdbc/driver/JdbcSupportEmitter.java
This PR stops reusing `java.sql.{Date, Timestamp}` objects used in `PreparedStatement.set{Date, Timestamp}()`.
Some JDBC driver implementations may holds `Date` or `Timestamp` objects, and the result may become different if these objects were changed after `PreparedStatement.set{Date, Timestamp}()` was invoked.
This implementation always creates a new `java.sql.{Date, Timestamp}` object.
N/A.
@akirakw
> Avoid reusing java.sql.{Date, Timestamp} objects.

- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/BatchTester.java
This PR fixes started time in `BatchTester`.
The latest implementation, the started time in `BatchTester` becomes each jobflow's started time. This should be the batch started time because jobflows may pass time values into the subsequent jobflows.
N/A.
N/A.
@akirakw
> Test start-date must be batch started time.

- windgate-project/asakusa-windgate-vocabulary/src/main/java/com/asakusafw/vocabulary/windgate/JdbcExporterDescription.java
- windgate-project/asakusa-windgate-vocabulary/src/main/java/com/asakusafw/vocabulary/windgate/JdbcImporterDescription.java
This PR removes unused optimization symbols in WindGate JDBC.
N/A.
We just removed `POSTGRES_COPY` which will not be implemented in the next release.
* #671 
@akirakw
> Remove unused optimization symbols in WindGate JDBC.

- dsl-project/asakusa-dsl-vocabulary/src/main/java/com/asakusafw/vocabulary/flow/util/CoreOperatorFactory.java
- dsl-project/asakusa-dsl-vocabulary/src/main/java/com/asakusafw/vocabulary/flow/util/CoreOperators.java
- mapreduce/compiler/core/src/main/java/com/asakusafw/compiler/flow/logging/LoggingFilter.java
- mapreduce/compiler/core/src/main/java/com/asakusafw/compiler/flow/plan/StagePlanner.java
This PR will fix MapReduce stage planner.
In the latest implementation, Asakusa on MapReduce compiler may generate a wrong execution plan when the application includes nested `confluent` operators.
This reduces such nested `confluent` operators before computing stage boundaries.
This PR also includes a new overload method of `CoreOperatorFactory.confluent()` with var args.
N/A.
@akirakw
> Fix MapReduce stage planner.

- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/io/csv/CsvFormatException.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/io/csv/CsvParser.java
- core-project/asakusa-runtime/src/test/java/com/asakusafw/runtime/io/csv/CsvParserTest.java
- directio-project/asakusa-directio-dmdl/src/main/java/com/asakusafw/dmdl/directio/csv/driver/CsvFormatEmitter.java
- windgate-project/asakusa-windgate-dmdl/src/main/java/com/asakusafw/dmdl/windgate/csv/driver/CsvSupportEmitter.java
This PR fixes to output incorrect line number or record number when target number is greater than MAX_INTEGER.
A variable type of line number in `CSVParser` is int, so this variable may be cyclic when line number exceeds MAX_INTEGER.
This PR changes variable type of line number and record number from int to long.
N/A
@ashigeru
> Fix to show wrong line number when over MAX_INT

- sdk-project/asakusa-sdk-app-core/pom.xml
- sdk-project/asakusa-sdk-core/pom.xml
This PR moves hadoop library dependency for sdk artifact from `asakusa-sdk-core` to `asakusa-sdk-app-core`
This improves dependency to more proper scope.
N/A.
N/A.
N/A.
> Move hadoop dependency in sdk artifact

- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/core/BatchContext.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/core/Report.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/core/api/ApiStub.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/core/api/BatchContextApi.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/core/api/ReportApi.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/core/api/package-info.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/core/legacy/LegacyBatchContext.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/core/legacy/LegacyReport.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/core/legacy/RuntimeResource.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/core/legacy/package-info.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/flow/MapperWithRuntimeResource.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/flow/ReducerWithRuntimeResource.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/flow/RuntimeResourceManager.java
- core-project/asakusa-runtime/src/main/resources/META-INF/services/com.asakusafw.runtime.core.RuntimeResource
- core-project/asakusa-runtime/src/main/resources/META-INF/services/com.asakusafw.runtime.core.legacy.RuntimeResource
- core-project/asakusa-runtime/src/test/java/com/asakusafw/runtime/core/ReportTest.java
- core-project/asakusa-runtime/src/test/java/com/asakusafw/runtime/core/api/ApiStubTest.java
- core-project/asakusa-runtime/src/test/java/com/asakusafw/runtime/flow/RuntimeResourceManagerTest.java
- core-project/asakusa-runtime/src/test/java/com/asakusafw/runtime/report/CommonsLoggingReportTest.java
- mapreduce/compiler/core/src/test/java/com/asakusafw/compiler/flow/processor/LoggingFlowProcessorTest.java
- sandbox-project/asakusa-directio-runtime-ext/src/main/java/com/asakusafw/runtime/directio/api/DirectIo.java
- sandbox-project/asakusa-directio-runtime-ext/src/main/java/com/asakusafw/runtime/directio/api/DirectIoApi.java
- sandbox-project/asakusa-directio-runtime-ext/src/main/java/com/asakusafw/runtime/directio/api/DirectIoDelegate.java
- sandbox-project/asakusa-directio-runtime-ext/src/main/java/com/asakusafw/runtime/directio/api/legacy/LegacyDirectIo.java
- sandbox-project/asakusa-directio-runtime-ext/src/main/java/com/asakusafw/runtime/directio/api/legacy/package-info.java
- sandbox-project/asakusa-directio-runtime-ext/src/main/resources/META-INF/services/com.asakusafw.runtime.core.RuntimeResource
- sandbox-project/asakusa-directio-runtime-ext/src/main/resources/META-INF/services/com.asakusafw.runtime.core.legacy.RuntimeResource
This PR introduces API stub classes into Asakusa Framework API entries.
In the latest implementation, each Framework API class has concrete implementation for MapReduce environment. This makes using framework API in other platforms such as Spark more difficult.
This introduces `API Stub` feature, which enables to replace framework API implementation with another one for the target platform. Note that, we have worked it out by replacing classes in the user application (a.k.a. API redirector).
N/A.
@akirakw
> Introduce API stub classes into Framework API.

- sdk-project/asakusa-sdk-app-core/pom.xml
- sdk-project/asakusa-sdk-app-directio/pom.xml
- sdk-project/asakusa-sdk-app-hive/pom.xml
- sdk-project/asakusa-sdk-app-windgate/pom.xml
- sdk-project/asakusa-sdk-test-core/pom.xml
This PR removes Asakusa on MapReduce related dependencies from SDK artifacts.
In the latest implementation, the SDK artifacts contain Asakusa on MapReduce related dependencies (e.g. Asakusa DSL compiler for MapReduce), even if Asakusa on MapReduce features is not required.
This just removes `com.asakusafw.mapreduce.compiler` group dependencies from the artifacts. To enable individual features, please use `asakusafw.sdk.*` convention which introduced in asakusafw/asakusafw-sdk#109.
* asakusafw/asakusafw-sdk#109
@akirakw
> Remove mapreduce related dependencies from SDK artifacts.

- mapreduce/compiler/core/src/main/java/com/asakusafw/compiler/flow/packager/FilePackager.java
- mapreduce/compiler/core/src/main/java/com/asakusafw/compiler/flow/processor/GroupSortFlowProcessor.java
- mapreduce/compiler/core/src/main/resources/META-INF/services/com.asakusafw.compiler.flow.FlowElementProcessor
This PR fixes DSL compiler for MapReduce (`./mapreduce`).
The DSL compiler for MapReduce had not recognized `GroupSort` operator.  It is an alias of `CoGroup` operator in the legacy operator DSL compiler implementation.
This adds `GroupSort` operator driver, and revise DSL compiler error messages for investigation.
N/A.
@akirakw
> Fix DSL compile for MapReduce.

- operator/builtin/src/main/java/com/asakusafw/operator/builtin/ConvertOperatorDriver.java
- operator/builtin/src/main/java/com/asakusafw/operator/builtin/DslBuilder.java
- operator/builtin/src/test/java/com/asakusafw/operator/builtin/ConvertOperatorDriverTest.java
- operator/core/src/main/java/com/asakusafw/operator/CompileEnvironment.java
- operator/core/src/main/java/com/asakusafw/operator/method/OperatorAnnotationProcessor.java
- operator/core/src/main/java/com/asakusafw/operator/method/OperatorFactoryEmitter.java
- operator/core/src/main/java/com/asakusafw/operator/method/OperatorImplementationEmitter.java
- operator/core/src/main/java/com/asakusafw/operator/model/OperatorDescription.java
- operator/core/src/main/java/com/asakusafw/operator/util/JavadocHelper.java
- operator/core/src/test/java/com/asakusafw/operator/method/OperatorFactoryEmitterTest.java
- operator/core/src/test/resources/com/asakusafw/operator/method/OperatorFactoryEmitterTest.files/com/example/WithVariable.java.txt
This PR fixes bug on operator DSL compiler (`./operator`).
The compiler works wrong if the application contains any of the following operators:
* `@Convert` -  had generated operators with wrong output port order.
* `@Branch` and `@MasterBranch` - had attempted to access to unsupported javadoc comment references  (and crashed).
N/A.
N/A.
@akirakw
> Fix operator DSL compiler for some operators.

- operator/builtin/src/test/java/com/asakusafw/operator/builtin/OperatorDriverTestRoot.java
- operator/core/src/main/java/com/asakusafw/operator/AbstractOperatorAnnotationProcessor.java
- operator/core/src/main/java/com/asakusafw/operator/CompileEnvironment.java
- operator/core/src/main/java/com/asakusafw/operator/CompilerOption.java
- operator/core/src/main/java/com/asakusafw/operator/WarningAction.java
- operator/core/src/main/java/com/asakusafw/operator/flowpart/FlowPartAnnotationProcessor.java
- operator/core/src/main/java/com/asakusafw/operator/method/OperatorAnnotationProcessor.java
- operator/core/src/main/java/com/asakusafw/operator/method/OperatorMethodAnalyzer.java
This PR introduce launch options to Asakusa operator DSL compiler (`./operator`).
The DSL compiler might have raised some noisy warnings if operator classes did not comply with strict DSL rules (e.g. the class is not declared as `abstract`). One of the introduced options can suppress their signals, or treat such classes as compile error.
Other options can turn on/off the compiler features temporarily (for only testing).
Application developers can specify options via asakusafw/asakusafw-sdk#115.
* `com.asakusafw.operator.warning`
* configure action for discouraged operator DSL code
* available options:
* `ignore`
* ignore warnings
* `report`
* report warnings
* `fail`
* fail on any warnings
* default: `report`
* asakusafw/asakusafw-sdk#115
@akirakw
> Introduce operator DSL compiler options.

- mapreduce/compiler/operator/pom.xml
This PR fixes lack of `com.asakusafw.runtime.core.Result` interface in Operator Compiler jar archive.
N/A.
N/A.
N/A.
N/A.
> Fix lack of Result interface in Operator Compiler

- operator/core/src/main/java/com/asakusafw/operator/model/OperatorDescription.java
- operator/core/src/main/java/com/asakusafw/operator/util/ElementHelper.java
- operator/core/src/test/java/com/asakusafw/operator/flowpart/FlowPartAnalyzerTest.java
- operator/core/src/test/java/com/asakusafw/operator/flowpart/FlowPartFactoryEmitterTest.java
- operator/core/src/test/resources/com/asakusafw/operator/flowpart/FlowPartAnalyzerTest.files/com/example/ctor/WithClass.java.txt
- operator/core/src/test/resources/com/asakusafw/operator/flowpart/FlowPartFactoryEmitterTest.files/com/example/WithClass.java.txt
This PR fixes type infer in operator DSL compiler (`./operator`).
The latest implementation, the compiler cannot recognize following a flow-part class:
```java
@FlowPart
public class F<
A extends ...,
B extends ...> extends FlowDescription {
public F(In<A> in, Out<B> out, Class<B> aClass) {
}
...
}
```
The above type variable `B` (in `Out<B>`) must be inferred by using `Class<B> aClass`, but the latest implementation had ignored the `Class<T>`.
N/A.
N/A,
@akirakw
> Fix type infer in operator DSL compiler.

- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/flow/FileMapListBuffer.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/io/util/DataIoUtils.java
- core-project/asakusa-runtime/src/test/java/com/asakusafw/runtime/flow/FileMapListBufferTest.java
This PR improves performance of `FileMapListBuffer` (a.k.a. `InputBuffer.ESCAPE`).
N/A.
We use NIO for reading/writing elements on temporary files.
N/A.
@akirakw
> Improve performance of `FileMapListBuffer`.

- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/value/StringOption.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/value/StringOptionUtil.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/value/ValueOption.java
- core-project/asakusa-runtime/src/test/java/com/asakusafw/runtime/value/StringOptionTest.java
- core-project/asakusa-runtime/src/test/java/com/asakusafw/runtime/value/StringOptionUtilTest.java
This PR introduces some utility methods about `StringOption`.
N/A.
This introduces the following new methods:
* `ValueOption<V <: ValueOption<V>>`
* `isPresent() : boolean`
* `orOption(V) : V`
* `StringOption`
* `isEmpty() : boolean`
* `contains({String, StringOption}) : boolean`
* `startsWith({String, StringOption}) : boolean`
* `endsWith({String, StringOption}) : boolean`
* `appendTo(StringBuilder) : StringBuilder`
* `StringOptionUtil`
* `countCodePoints() : int`
* `parseInt(StringOption) : int`
* `parseLong(StringOption) : long`
* `parseDecimal(StringOption) : BigDecimal`
N/A.
@akirakw
> Add utility methods for StringOption.

- dmdl-project/asakusa-dmdl-core/pom.xml
- utils-project/java-dom/pom.xml
- utils-project/javadoc-parser/pom.xml
This PR fixes artifact id of JFlex Maven Plugin in pom.xml of some projects.
This plugin's id was previously `maven-jflex-plugin` but `jflex-maven-plugin` is current artifact id
(see: http://jflex.sourceforge.net/jflex-maven-plugin ).
N/A.
N/A.
N/A.
N/A.
> Fix artifact id of JFlex Maven Plugin

- README.md
This PR removes a link to `asakusafw-dag` repository in README.md.
`asakusafw-dag` has been migrated to `asakusafw-compiler/dag` as a sub-project.
N/A.
* asakusafw/asakusafw-compiler#82
@akirakw
> Remove reference to old DAG project in README file.

- dmdl-project/asakusa-dmdl-core/src/main/java/com/asakusafw/dmdl/model/AstAttributeValueMap.java
- dmdl-project/asakusa-dmdl-core/src/main/java/com/asakusafw/dmdl/model/AstLiteral.java
- dmdl-project/asakusa-dmdl-core/src/main/java/com/asakusafw/dmdl/model/AstNode.java
- dmdl-project/asakusa-dmdl-core/src/main/java/com/asakusafw/dmdl/parser/DmdlEmitter.java
- dmdl-project/asakusa-dmdl-core/src/main/javacc/DmdlParser.jj
- dmdl-project/asakusa-dmdl-core/src/test/java/com/asakusafw/dmdl/parser/DmdlParserTest.java
- dmdl-project/asakusa-dmdl-core/src/test/resources/com/asakusafw/dmdl/parser/map.txt
This PR introduces attribute value map syntax into DMDL.
In the latest implementation, DMDL attributes can include following values:
* literal
* name
* array of values
This PR introduces *map of values* as a new attribute value type that has pairs of key (as literal) and other attribute values.
This introduces a new grammer rule `<attribute-value-map>` which can appear in DMDL attributes.
```
<attribute-value>:
...
<attribute-value-map>
...
<attribute-value-map>:
'{' ':' '}'
'{' <attribute-pair-list> ','? '}'
<attribute-pair-list>:
<attribute-pair-list> ',' <attribute-pair>
<attribute-pair>
<attribute-pair>:
<literal> ':' <attribute-value>
```
Note that, empty maps must be `{ : }`, because `{ }` represents an empty array.
Here an example of attribute value map.
```
@some.attr(
map = { …
```
> Introduce attribute value map syntax into DMDL.

- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/flow/FileMapListBuffer.java
This PR fixes assertion in `FileMapListBuffer`.
The latest implementation sometimes raise `AssertionError` when the internal buffer was full, but it must be "the buffer page is not empty".
N/A.
* #696 
@akirakw
> Fix validating buffer contents.

- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/directio/BinaryStreamFormat.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/directio/hadoop/HadoopDataSourceCore.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/directio/hadoop/HadoopDataSourceUtil.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/directio/hadoop/HadoopFileFormat.java
- directio-project/asakusa-directio-dmdl/src/main/java/com/asakusafw/dmdl/directio/csv/driver/CsvFormatEmitter.java
- directio-project/asakusa-directio-dmdl/src/test/java/com/asakusafw/dmdl/directio/csv/driver/CsvFormatEmitterTest.java
- hive-project/asakusa-hive-core/src/main/java/com/asakusafw/directio/hive/orc/AbstractOrcFileFormat.java
- hive-project/asakusa-hive-core/src/main/java/com/asakusafw/directio/hive/orc/OrcFileInput.java
- hive-project/asakusa-hive-core/src/main/java/com/asakusafw/directio/hive/parquet/AbstractParquetFileFormat.java
- hive-project/asakusa-hive-core/src/main/java/com/asakusafw/directio/hive/parquet/ParquetFileInput.java
- sandbox-project/asakusa-directio-dmdl-ext/src/main/java/com/asakusafw/dmdl/directio/tsv/driver/TsvFormatEmitter.java
- sandbox-project/asakusa-directio-dmdl-ext/src/test/java/com/asakusafw/dmdl/directio/tsv/driver/TsvFormatEmitterTest.java
- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/DirectIoUtil.java
- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/DriverElementBase.java
- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/FlowDriverInput.java
- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/FlowDriverOutput.java
- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/OperatorTestEnvironment.java
- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/DirectIoUtilTest.java
- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/FlowDriverInputTest.java
- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/FlowDriverOutputTest.java
- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/FlowDriverPortTestHelper.java
- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/MockFlowDriverInput.java
- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/MockFlowDriverOutput.java
- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/MockTestDataToolProvider.java
- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/OperatorTestEnvironmentTest.java
- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/testing/dsl/SimpleFileFormat.java
- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/testing/dsl/SimpleStreamFormat.java
- testing-project/asakusa-test-driver/src/test/resources/com/asakusafw/testdriver/directio/simple.txt
This PR enables Direct I/O `DataFormat` for test inputs.
N/A.
This introduces the following new methods:
* `{FlowPart,JobFlow}Driver{Input,Output}<T>`
* `prepare(Class<? extends DataFormat<? super T>> formatClass, File sourceFile)`
* load the given file
* `prepare(Class<? extends DataFormat<? super T>> formatClass, String sourcePath)`
* load a file on the classpath (relative from the test class)
* `OperatorTestEnvironment`
* `loader(Class<T> dataType, Class<? extends DataFormat<? super T>> formatClass, File file)`
* load the given file
* `loader(Class<T> dataType, Class<? extends DataFormat<? super T>> formatClass, String path)`
* load a file on the classpath (relative from the test class)
Note that, the "file name" may be changed if the given source path is type of `String`, so that use …
> Enable Direct I/O `DataFormat` for test inputs.

- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/testing/moderator/MockExporterRetriever.java
This PR fix tests about `asakusa-test-driver` itself.
`MockExporterRetriever#truncate` may leave old outputs, and then their consequent tests would fail.
N/A.
N/A.
@akirakw
> Fix tests in asakusa-test-driver.

- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/OperatorTestEnvironment.java
This PR introduces `OperatorTestEnvironment.newResult()` that provides `MockResult` object for testing operator methods.
`MockResult` is a mock of `Result` for testing operator methods to capture test outputs of `@Extract`, `@CoGroup`, or etc.
The introduced `OperatorTestEnvironment.newResult()` returns `MockResult` which always creates copies of added objects (see [MockResult.bless()](http://docs.asakusafw.com/0.9.0/release/api/com/asakusafw/runtime/testing/MockResult.html#bless-T-)).
N/A.
N/A.
@akirakw see http://asakusafw.s3.amazonaws.com/documents/latest/develop/ja/html/testing/user-guide.html#id5
> Introduce `OperatorTestEnvironment.newResult()`.

- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/DirectIoUtil.java
- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/loader/BasicDataLoader.java
- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/loader/BasicGroupLoader.java
- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/loader/Util.java
This PR revises error messages in `asakusa-test-driver`.
Recently introduced features (`OperatorTestEnvironment.loader`, `DataFormat` for test data) may throw an error with confusable messages. This will make them better.
N/A.
* #700
* #701
* #704
@akirakw
> Revise error messages about wrong test data.

- utils-project/java-dom/src/main/java/com/asakusafw/utils/java/internal/model/syntax/ConstructorReferenceExpressionImpl.java
- utils-project/java-dom/src/main/java/com/asakusafw/utils/java/internal/model/syntax/MethodReferenceExpressionImpl.java
- utils-project/java-dom/src/main/java/com/asakusafw/utils/java/internal/model/syntax/ModelFactoryImpl.java
- utils-project/java-dom/src/main/java/com/asakusafw/utils/java/internal/model/util/ModelDigester.java
- utils-project/java-dom/src/main/java/com/asakusafw/utils/java/internal/model/util/ModelEmitter.java
- utils-project/java-dom/src/main/java/com/asakusafw/utils/java/internal/model/util/ModelMatcher.java
- utils-project/java-dom/src/main/java/com/asakusafw/utils/java/model/syntax/ConstructorReferenceExpression.java
- utils-project/java-dom/src/main/java/com/asakusafw/utils/java/model/syntax/Expression.java
- utils-project/java-dom/src/main/java/com/asakusafw/utils/java/model/syntax/MethodOrConstructorReferenceExpression.java
- utils-project/java-dom/src/main/java/com/asakusafw/utils/java/model/syntax/MethodReferenceExpression.java
- utils-project/java-dom/src/main/java/com/asakusafw/utils/java/model/syntax/ModelFactory.java
- utils-project/java-dom/src/main/java/com/asakusafw/utils/java/model/syntax/ModelKind.java
- utils-project/java-dom/src/main/java/com/asakusafw/utils/java/model/syntax/PropertyKind.java
- utils-project/java-dom/src/main/java/com/asakusafw/utils/java/model/syntax/StrictVisitor.java
- utils-project/java-dom/src/main/java/com/asakusafw/utils/java/model/syntax/TypeOrExpression.java
- utils-project/java-dom/src/main/java/com/asakusafw/utils/java/model/syntax/Visitor.java
- utils-project/java-dom/src/main/java/com/asakusafw/utils/java/model/util/ExpressionBuilder.java
- utils-project/java-dom/src/main/java/com/asakusafw/utils/java/model/util/TypeBuilder.java
- utils-project/java-dom/src/test/java/com/asakusafw/utils/java/internal/model/util/ModelEmitterTest.java
This PR adds method reference expression into Java DOM.
In #665, we added lambda expressions (`x -> f(x)`) into Java DOM library, but we forgot to add method reference expressions (`Some::method`).
This introduces the two key interfaces `MethodReferenceExpression` and `ConstructorReferenceExpression`. The former can refer methods, and the latter refer constructors (`Some::new`). Because `new` is a reserved word, `MethodReferenceExpression` cannot handle it as a method name in the current implementation.
* #665
N/A.
> Add Java DOM for method reference expressions.

- testing-project/asakusa-test-driver/pom.xml
- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/DirectIoUtil.java
- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/DriverElementBase.java
- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/FlowDriverOutput.java
- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/DirectIoUtilTest.java
- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/FlowDriverInputTest.java
- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/FlowDriverOutputTest.java
- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/testing/dsl/SimpleStreamFormat.java
This PR enable Direct I/O `DataFormat` to keep test outputs (a.k.a. `dumpActual()`).
#701 and #704 have introduced Direct I/O `DataFormat` to generate test input data and expected output data. This additionally enables it for saving actual output data onto the local file system.
It may helps application developers to inspect the results by using external facilities.
This introduces the following new method:
* `{FlowPart,JobFlow}DriverOutput<T>.dumpActual(Class<? extends DataFormat<? super T>> formatClass, File expectedFile)`
* saves the actual output data into the given file
Note that, this does not introduce `dumpActual(Class<? extends DataFormat<? super T>>, String)`, because this only supports local file system as its output target.
* #701 
* #704 
@akirakw
> Enable Direct I/O `DataFormat` to keep test outputs.

- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/io/text/csv/CsvFieldReader.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/io/text/csv/CsvFieldWriter.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/io/text/csv/CsvTextFormat.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/io/text/csv/LineCursor.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/io/text/csv/QuoteStyle.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/io/text/csv/package-info.java
- core-project/asakusa-runtime/src/test/java/com/asakusafw/runtime/io/text/csv/CsvFieldReaderTest.java
- core-project/asakusa-runtime/src/test/java/com/asakusafw/runtime/io/text/csv/CsvFieldWriterTest.java
- core-project/asakusa-runtime/src/test/java/com/asakusafw/runtime/io/text/csv/CsvTextFormatTest.java
- core-project/asakusa-runtime/src/test/java/com/asakusafw/runtime/io/text/csv/LineCursorTest.java
- directio-project/asakusa-directio-dmdl/src/main/java/com/asakusafw/dmdl/directio/text/AbstractTextStreamFormatGenerator.java
- directio-project/asakusa-directio-dmdl/src/main/java/com/asakusafw/dmdl/directio/text/QuoteSettings.java
- directio-project/asakusa-directio-dmdl/src/main/java/com/asakusafw/dmdl/directio/text/TextFieldSettings.java
- directio-project/asakusa-directio-dmdl/src/main/java/com/asakusafw/dmdl/directio/text/TextFormatConstants.java
- directio-project/asakusa-directio-dmdl/src/main/java/com/asakusafw/dmdl/directio/text/csv/CsvTextDriver.java
- directio-project/asakusa-directio-dmdl/src/main/java/com/asakusafw/dmdl/directio/text/csv/CsvTextEmitter.java
- directio-project/asakusa-directio-dmdl/src/main/java/com/asakusafw/dmdl/directio/text/csv/CsvTextTrait.java
- directio-project/asakusa-directio-dmdl/src/main/java/com/asakusafw/dmdl/directio/text/csv/Messages.java
- directio-project/asakusa-directio-dmdl/src/main/java/com/asakusafw/dmdl/directio/text/csv/package-info.java
- directio-project/asakusa-directio-dmdl/src/main/resources/META-INF/services/com.asakusafw.dmdl.java.spi.JavaDataModelDriver
- directio-project/asakusa-directio-dmdl/src/main/resources/META-INF/services/com.asakusafw.dmdl.spi.AttributeDriver
- directio-project/asakusa-directio-dmdl/src/main/resources/com/asakusafw/dmdl/directio/text/csv/messages.properties
- directio-project/asakusa-directio-dmdl/src/main/resources/com/asakusafw/dmdl/directio/text/messages.properties
- directio-project/asakusa-directio-dmdl/src/test/java/com/asakusafw/dmdl/directio/text/csv/CsvTextEmitterTest.java
This PR introduces a brand new implementation of CSV format support to Direct I/O.
This implementation is more customizable than the existing CSV implementation.
The new implementation is easier to customize its format than the existing one. It shares almost implementation with Direct I/O delimited text (#713), and has the following features:
* record separated by line delimiter (LF, CR, or CR+LF)
* configurable field separator
* configurable quote style
* configurable file header
* configurable value format
* configurable error actions
* and more
Note that, the new implementation will be a bit slower than the existing implementation. Please continue to use the existing implementation if it is enough.
This introduces a new DMDL attribute `@directio.text.csv` for data models (the existing …
> Add another CSV text format support for Direct I/O.

- directio-project/asakusa-directio-dmdl/src/main/java/com/asakusafw/dmdl/directio/text/AttributeAnalyzer.java
- directio-project/asakusa-directio-dmdl/src/main/java/com/asakusafw/dmdl/directio/text/delimited/DelimitedTextEmitter.java
- directio-project/asakusa-directio-dmdl/src/test/java/com/asakusafw/dmdl/directio/text/delimited/DelimitedTextEmitterTest.java
`@directio.text.delimited(escape_line_separator)` does not work correct for `false`.
N/A.
N/A.
* #713 
@akirakw
> Fix `escape_line_separator=false`.

- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/stage/directio/StringTemplate.java
- core-project/asakusa-runtime/src/test/java/com/asakusafw/runtime/stage/directio/StringTemplateTest.java
- mapreduce/compiler/directio/src/main/java/com/asakusafw/compiler/directio/OutputPattern.java
- mapreduce/compiler/directio/src/test/java/com/asakusafw/compiler/directio/OutputPatternTest.java
Resource pattern of Direct I/O file output now can accept decimal format (`DecimalFormat`).
`DirectFileOutputDescription.getResourcePattern()` can contain `{placeholder:format}` but `format` is only available for `DATE` and `DATETIME` properties.
Here, the PR introduces the *format* for numeric properties, `BYTE`, `SHORT`, `INT`, `LONG`, `FLOAT`, `DOUBLE`, and `DECIMAL`. The format pattern must be `DecimalFormat`. 
This commit only activates the feature for Asakusa on MapReduce.
N/A.
@akirakw
> Resource pattern of direct output now can accept decimal format.

- directio-project/asakusa-directio-dmdl/src/main/java/com/asakusafw/dmdl/directio/csv/driver/CsvFormatEmitter.java
- sandbox-project/asakusa-directio-dmdl-ext/src/main/java/com/asakusafw/dmdl/directio/tsv/driver/TsvFormatEmitter.java
This PR removes dead-code in generated `~CsvFormat` (`@directio.csv`).
If input splitting is disabled, generated `~CsvFormat` contained
redundant assignment:
```java
InputStream fragmentInput = fragmentInput = ...;
```
N/A.
N/A.
> Remove deadcode in generated `CsvFormat` (v1).

- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/DirectIoUtilTest.java
- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/FileSystemCleaner.java
- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/FlowDriverInputTest.java
- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/FlowDriverOutputTest.java
- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/OperatorTestEnvironmentTest.java
- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/TesterTestRoot.java
- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/loader/BasicDataLoaderTest.java
- testing-project/asakusa-test-moderator/src/main/java/com/asakusafw/testdriver/hadoop/ConfigurationFactory.java
This PR makes testing `asakusa-test-driver` project more stable.
`asakusa-test-driver` project replaces the Hadoop local file system implementation with `AsakusaTestLocalFileSystem` instead of `LocalFileSystem` in almost of its test cases, but several test cases introduced in `0.9.1` still use `LocalFileSystem`. If test cases with using `LocalFileSystem` run before other tests, Hadoop keeps a `LocalFileSystem` object as cache for the default local file system. And it may leak into other test cases which requires `AsakusaTestLocalFileSystem`. 
We introduced `FileSystemCleaner` class that removes all Hadoop file system caches, and apply it before/after running each test case.
N/A.
> Make testing `asakusa-test-driver` more stable.

- windgate-project/asakusa-windgate-core/src/main/java/com/asakusafw/windgate/core/ProfileContext.java
- windgate-project/asakusa-windgate-hadoopfs/src/main/java/com/asakusafw/windgate/hadoopfs/HadoopFsProvider.java
- windgate-project/asakusa-windgate-hadoopfs/src/main/java/com/asakusafw/windgate/hadoopfs/jsch/JschHadoopFsProvider.java
- windgate-project/asakusa-windgate-test-inprocess/src/main/java/com/asakusafw/testdriver/windgate/emulation/AbstractWindGateCommandEmulator.java
This PR fixes WindGate in-process testing to pass a valid Hadoop configuration object.
Disabling the Hadoop local file system cache in #725 makes in-process test execution more strict, and WindGate `hadoop.*` resources had used an incorrect configuration object.
We enhanced WindGate in-process boot strap (`AbstractWindGateCommandEmulator`) to pass a well configured Hadoop configuration object into `hadoop.*` resources.
* #725
> Fix WindGate inprocess testing to pass a valid Hadoop conf.

- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/stage/temporary/TemporaryStorage.java
This PR revises debug log in `TemporaryStorage` class for printing actual data path of their inputs and outputs.
N/A.
Here is an example of logback configuration for enabling this logs.
```xml
<configuration>
...
<logger name="com.asakusafw.runtime.stage.temporary.TemporaryStorage" level="DEBUG" />
...
</configuration>
```
* #727
> Revise debug logs of `TemporaryStorage`.

- mapreduce/compiler/cli/src/main/java/com/asakusafw/compiler/bootstrap/AllBatchCompilerDriver.java
This PR suppresses class resolutions when MapReduce compiler searches for source classes.
In the latest implementation, MapReduce compiler always resolves the compilation target classes.
We use `Class.forName(name, false, classLoader)` instead of `Class.forName(name)`.
N/A.
> Suppress class resolution on searching for batch classes.

- pom.xml
This PR fixes javadoc build error after merged #732.
N/A.
This excludes `dmdl.parser` package generated from JavaCC.
N/A.
> Exclude dmdl.parser package from javadoc

- windgate-project/asakusa-windgate-core/src/main/java/com/asakusafw/windgate/core/vocabulary/JdbcProcess.java
- windgate-project/asakusa-windgate-vocabulary/src/main/java/com/asakusafw/vocabulary/windgate/JdbcImporterDescription.java
This PR introduces a new WindGate JDBC optimization option `Option.ORACLE_PARTITION` to `JdbcImporterDescription`.
see asakusafw/asakusafw-compiler#128
This option is currently available only in WindGate JDBC *direct mode*. 
* asakusafw/asakusafw-compiler#128
> Add `Option.ORACLE_PARTITION` to `JdbcImporterDescription`.

- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/directio/hadoop/HadoopDataSourceUtil.java
- testing-project/asakusa-test-data-provider/src/test/java/com/asakusafw/testdriver/excel/ExcelSheetSinkTest.java
This PR fixes code style for Eclipse 4.7.
Java compiler in Eclipse 4.7 has been changed from 4.6. It becomes to raise some new warnings/errors.
N/A.
N/A.
> Fix code style for Eclipse 4.7.

- gradle/src/main/groovy/com/asakusafw/gradle/plugins/EclipsePluginEnhancement.groovy
- gradle/src/main/groovy/com/asakusafw/gradle/plugins/internal/AsakusaSdkPlugin.groovy
This PR promotes the new operator DSL compiler implementation.
The new operator DSL compiler has been introduced since `0.9.0`, and it requires `asakusafw.sdk.incubating true`. This PR enables the feature even if `incubating false`.
N/A.
* #663
> Enable new operator DSL compiler implementation in default.

- workflow/hadoop/src/test/java/com/asakusafw/workflow/cli/hadoop/BridgeDeleteTaskExecutorTest.java
- workflow/hadoop/src/test/java/com/asakusafw/workflow/cli/hadoop/BridgeHadoopTaskExecutorTest.java
This PR fixes test cases for Windows.
#746 and #747 includes several test cases which do not work correct on Windows related to difference of path name separator character (`/` or `\`).
N/A.
* #746 
* #747
> Fix test case for Windows.

- operation-project/command-portal/src/main/dist/bin/asakusa
- operation-project/command-portal/src/main/dist/bin/asakusa.cmd
- pom.xml
This PR introduces `bin/asakusa.cmd` which is portal command entry for Windows platform.
The portal command introduced in #747 and #750 is only for Unix like environment because its entry is a bash script. We now introduce `asakusa.cmd` which is written as Windows batch file. Note that, `asakusa run` does not work correct, but other commands like `list` will be work.
N/A.
* #747 
* #750
> Add `bin/asakusa.cmd` for Windows.

- pom.xml
This PR bumps the Gradle tooling API version to 4.1, used in each integration test.
#753 did not change the Gradle tooling API version.
N/A.
* #753
> Bump Gradle tooling API version to 4.1.

- integration/src/integration-test/java/com/asakusafw/integration/core/DirectIoToolsTest.java
- integration/src/integration-test/java/com/asakusafw/integration/core/OperationToolsTest.java
- integration/src/integration-test/java/com/asakusafw/integration/core/WindGateTest.java
- integration/src/integration-test/java/com/asakusafw/integration/core/YaessTest.java
- integration/src/main/java/com/asakusafw/integration/PlatformUtil.java
- windgate-project/bootstrap/src/main/java/com/asakusafw/windgate/bootstrap/FinalizeBootstrap.java
This PR fixes integration test for Windows platform.
See #752.
This also fixed WindGate finalizer for Windows. It had been crashed if session ID (a.k.a. execution ID) was not specified.
* #752
> Fix integration test for Windows.

- gradle/src/main/groovy/com/asakusafw/gradle/plugins/internal/AsakusaSdkPlugin.groovy
This PR is fix of #756, it must inject tool launcher classpath into each Gradle task.
#756 enables `TestToolTask` to use tool launcher, but tool launcher classpath was not given.
N/A.
* #756
> Inject tool launcher classpath.

- gradle/src/main/resources/META-INF/asakusa-gradle/defaults.properties
- gradle/src/test/groovy/com/asakusafw/gradle/plugins/AsakusaUpgradeTest.groovy
This PR bumps up Gradle version for application projects to `4.1`.
N/A.
N/A.
N/A.
> Bump Gradle version for application projects to 4.1.

- gradle/build.gradle
This PR bumps up Gradle required JDK version to 1.8.
Asakusa Framework has been required Java `>= 1.8` in recent versions, but application Gradle does not require `1.8` for backward compatibility.
Note that, we remove `project.targetCompatibility` in `build.gradle` because it inherits `project.sourceCompatibility` in default.
N/A.
> Bump Gradle required Java version to 1.8.

- workflow/cli/src/main/java/com/asakusafw/workflow/cli/run/RunCommand.java
- workflow/executor/src/main/java/com/asakusafw/workflow/executor/basic/BasicJobflowExecutor.java
This PR revises error messages in `asakusa run`.
In the latest implementation, `asakusa run` drops root causal information of errors.
N/A.
* #757
> Revise error messages in `asakusa run`.

- gradle/src/main/groovy/com/asakusafw/gradle/plugins/internal/AsakusafwOrganizer.groovy
- integration/src/integration-test/java/com/asakusafw/integration/core/SetupToolsTest.java
- operation-project/pom.xml
- operation-project/setup-tools/.gitignore
- operation-project/setup-tools/pom.xml
- operation-project/setup-tools/src/main/java/com/asakusafw/operation/tools/setup/MakeExecutable.java
- operation-project/setup-tools/src/main/java/com/asakusafw/operation/tools/setup/Setup.java
- operation-project/setup-tools/src/main/java/com/asakusafw/operation/tools/setup/package-info.java
This PR introduces post installation script onto `tools/bin/setup.jar`.
The introduced script makes Asakusa Framework installation (which typically it is on `$ASAKUSA_HOME`) available. Archivers sometimes removes file permissions from Asakusa deployment archives, and then the script restores executable permissions of commands in the installation. Since the latest version, each command name must ends with `.sh`, and users simply restore executable permission by `find . -name '*.sh' | xargs ...`. However, recent commits like #752 removes the common file extension of these commands. This introduced script will replace that operation.
```
Usage:
java -jar $ASAKUSA_HOME/tools/bin/setup.jar
Processes the default installation (ASAKUSA_HOME=/Users/arakawa/target/asakusa/home).
java -jar …
```
> Introduce `tools/bin/setup.jar`.

- gradle/src/main/groovy/com/asakusafw/gradle/plugins/internal/AsakusafwOrganizer.groovy
- hive-project/asakusa-hive-core/pom.xml
This PR fixes Direct I/O Hive since #744.
In #744, we replaced `asakusa-hive-info` with `com.asakusafw.info:asakusa-info-hive`, but the Framework Organizer still refer the old library.
This PR introduces a composite bundle to `com.asakusafw:asakusa-hive-info` as `lib` classifier. It also includes the required dependencies of Direct I/O Hive feature except the Hive core library.
* #744
> Fix regression (Direct I/O Hive).

- operation-project/command-portal/src/main/dist/bin/asakusa
- operation-project/command-portal/src/main/dist/bin/asakusa.cmd
- operation-project/directio/src/main/dist/tools/bin/directio
- operation-project/directio/src/main/dist/tools/bin/directio.cmd
- operation-project/directio/src/main/java/com/asakusafw/operation/tools/directio/file/FileGetCommand.java
- operation-project/directio/src/main/java/com/asakusafw/operation/tools/directio/file/FilePutCommand.java
- utils-project/jcommander-wrapper/src/main/java/com/asakusafw/utils/jcommander/JCommanderWrapper.java
- utils-project/jcommander-wrapper/src/test/java/com/asakusafw/utils/jcommander/JCommanderWrapperTest.java
This PR improves usage of `tools/bin/directio` command introduced since #765.
See #765.
This PR includes the following revisions:
* `tools/bin/directio` script is now relocatable (only depends on `ASAKUSA_HOME`)
* better parsing command line options
* accepts combined short-name options like `-vrw` => `-v -r -w`
* rejects unknown options instead of recognize as main parameters
* fix `put` command
* fix typo
* #765
> Revise `tools/bin/directio` command.

- gradle/src/main/groovy/com/asakusafw/gradle/plugins/internal/AsakusaSdkPlugin.groovy
- gradle/src/main/groovy/com/asakusafw/gradle/plugins/internal/AsakusafwOrganizer.groovy
This PR fixes regressions about hive-exec library references in Gradle plug-ins.
(1) `sdk.hive true` brings incorrect `hive-exec` library (it must be `1.1.1`, but uses `1.2.1` from `asakusa-hive-core`).
(2) `asakusafwOrganizer.hive.libraries` introduces transitive dependencies.
N/A.
N/A.
> Fix hive-exec reference in Gradle plug-ins.

- hive-project/asakusa-hive-core/src/main/java/com/asakusafw/directio/hive/parquet/DecimalValueDriver.java
- hive-project/asakusa-hive-core/src/main/java/com/asakusafw/directio/hive/parquet/ParquetFileInput.java
This PR fixes Direct I/O Hive for recent distributions like CDH 5.x.
Recent parquet libraries include some binary incompatible changes since Hive `1.2.1`. 
This includes the following fixes:
* replace `PrimitiveBuilder.{precision,scale,length}` invocation with reflective operation, because they have been lost their binary compatibility
* replace `ParquetFileReader.new` invocation with reflective operation, because it raises warning logs
N/A.
> Fix Direct I/O Hive for recent distributions.

- hive-project/asakusa-hive-core/src/main/java/com/asakusafw/directio/hive/parquet/AbstractParquetFileFormat.java
- hive-project/asakusa-hive-core/src/main/java/com/asakusafw/directio/hive/parquet/ParquetFileInput.java
This PR removes use of deprecated method in Direct I/O HIve.
The following methods have been introduced since Hive `1.1.0`:
* `ParquetFileReader.readAllFootersInParallel` with `skipRowGroups`
* `ParquetFileReader.readFooter` with `ParquetMetadataConverter`
The above methods improves performance by filtering some metadata, and the existing methods have become deprecated. We now use the introduced methods instead of deprecated (require Hive `>= 1.1.0`).
N/A.
N/A.
> Remove use of deprecated methods in Direct I/O hive.

- info/cli/src/main/java/com/asakusafw/info/cli/hive/HiveDdlCommand.java
- info/cli/src/main/java/com/asakusafw/info/cli/hive/HiveGroup.java
- info/cli/src/main/java/com/asakusafw/info/cli/hive/HiveIoParameter.java
- info/cli/src/main/java/com/asakusafw/info/cli/hive/HiveTableParameter.java
- info/cli/src/main/java/com/asakusafw/info/cli/hive/LocationMapper.java
- info/cli/src/main/java/com/asakusafw/info/cli/hive/LocationParameter.java
- info/cli/src/main/java/com/asakusafw/info/cli/hive/package-info.java
- info/cli/src/main/resources/META-INF/services/com.asakusafw.utils.jcommander.common.CommandProvider
- integration/src/integration-test/java/com/asakusafw/integration/core/OperationToolsTest.java
This PR introduces `asakusa hive` command group.
The introduces command group includes `ddl` sub-command that generates Hive DDL script from `batch-info.json` files.
Note that, this command is currently experimental. The command name will be changed in future.
N/A.
> Add `asakusa hive` command group.

- info/cli/src/main/java/com/asakusafw/info/cli/generate/GenerateGroup.java
- info/cli/src/main/java/com/asakusafw/info/cli/generate/ddl/DdlGroup.java
- info/cli/src/main/java/com/asakusafw/info/cli/generate/ddl/DdlHiveCommand.java
- info/cli/src/main/java/com/asakusafw/info/cli/generate/ddl/HiveIoParameter.java
- info/cli/src/main/java/com/asakusafw/info/cli/generate/ddl/HiveTableParameter.java
- info/cli/src/main/java/com/asakusafw/info/cli/generate/ddl/LocationMapper.java
- info/cli/src/main/java/com/asakusafw/info/cli/generate/ddl/LocationParameter.java
- info/cli/src/main/java/com/asakusafw/info/cli/generate/ddl/package-info.java
- info/cli/src/main/java/com/asakusafw/info/cli/generate/dot/DotGroup.java
- info/cli/src/main/java/com/asakusafw/info/cli/generate/dot/DotParameter.java
- info/cli/src/main/java/com/asakusafw/info/cli/generate/dot/DrawEngine.java
- info/cli/src/main/java/com/asakusafw/info/cli/generate/dot/DrawJobflowCommand.java
- info/cli/src/main/java/com/asakusafw/info/cli/generate/dot/DrawOperatorCommand.java
- info/cli/src/main/java/com/asakusafw/info/cli/generate/dot/DrawPlanCommand.java
- info/cli/src/main/java/com/asakusafw/info/cli/generate/dot/Drawer.java
- info/cli/src/main/java/com/asakusafw/info/cli/generate/dot/ShowAllParameter.java
- info/cli/src/main/java/com/asakusafw/info/cli/generate/dot/package-info.java
- info/cli/src/main/java/com/asakusafw/info/cli/generate/package-info.java
- info/cli/src/main/resources/META-INF/services/com.asakusafw.utils.jcommander.common.CommandProvider
- integration/src/integration-test/java/com/asakusafw/integration/core/OperationToolsTest.java
- utils-project/jcommander-wrapper/src/main/java/com/asakusafw/utils/jcommander/CommandBuilder.java
- utils-project/jcommander-wrapper/src/main/java/com/asakusafw/utils/jcommander/JCommanderWrapper.java
This PR renames `asakusa` command groups.
`asakusa hive` command introduced #774 is out of alignment from the existing command groups, so that we rearrange some commands.
* `asakusa draw ...` -> `asakusa generate dot ...`
* `asakusa hive ddl` -> `asakusa generate ddl hive`
* `asakusa hive {input,output}` -> N/A
* they are alias of `asakusa list hive {input,output}`
Finally, `asakusa` has the following command groups:
```
generate - Generates resources from DSL information.
list - Displays DSL information as list style.
run - Runs a batch application.
```
Note that, some integration tests in the downstream projects will be broken.
* #774
> Rename `asakusa` command groups.

- info/cli/src/main/java/com/asakusafw/info/cli/common/ApplicationBaseDirectoryParameter.java
- info/cli/src/main/java/com/asakusafw/info/cli/common/BatchInfoParameter.java
- operation-project/command-portal/src/main/dist/bin/asakusa
- operation-project/command-portal/src/main/dist/bin/asakusa.cmd
- operation-project/directio/src/main/java/com/asakusafw/operation/tools/directio/common/ConfigurationParameter.java
- operation-project/directio/src/main/java/com/asakusafw/operation/tools/directio/file/LocalPathParameter.java
- utils-project/jcommander-wrapper/src/main/java/com/asakusafw/utils/jcommander/common/LocalPath.java
- utils-project/jcommander-wrapper/src/main/java/com/asakusafw/utils/jcommander/common/OutputParameter.java
- workflow/cli/src/main/java/com/asakusafw/workflow/cli/common/WorkflowParameter.java
This PR fixes `--output` option of `asakusa` command. Its relative path will be resolved as wrong path.
`asakusa` command always works on the `$HOME` (or `%USERPROFILE%`) directory because `asakusa run` requires such the working directory, but it also makes relative paths wrong.
We keeps the original working directory into the environment variable `CALLER_CWD`, and resolves each relative path with the original one.
This PR will fix the following local paths:
* `--output` parameter of `asakusa` and `directio` command
* `--batchapps` parameter of `asakusa` command
* `--configuration` parameter of `directio` command
* Batch application directories in `asakusa` command parameter
* #750 
* #765
> Fix base dir of `--output` in `asakusa` command.

- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/loader/BasicGroupLoader.java
This PR fixes error messages of `GroupView.find()` with inconsistent argument types on tests.
`OperatorTestEnvironment.loader()` can provide `GroupLoader`s but it `.find()` methods will raise error with confusing messages when argument types are wrong.
N/A.
> Fix error messages of views with invalid types on tests.

- operator/builtin/src/main/java/com/asakusafw/operator/builtin/DslBuilder.java
- operator/builtin/src/test/java/com/asakusafw/operator/builtin/CoGroupOperatorDriverTest.java
- operator/builtin/src/test/resources/com/asakusafw/operator/builtin/CoGroupOperatorDriverTest.files/com/example/ViolateWithInputView.java.txt
This PR fixes operator compiler to raise errors for `@CoGroup` operator without standard inputs.
The latest implementation does not raise errors for the following method:
```java
@CoGroup
public void method(@Key(group = "content") GroupView<Model> in, Result<Proceeded> out) {
...
}
```
It must have one or more input parameters other than views.
The compiler has also assumed views as standard inputs. It slips through operator input validation - each operator must have one or more inputs.
N/A.
> CoGroup with no input (but views) should be compile error.

- workflow/cli/src/main/java/com/asakusafw/workflow/cli/run/ExecutorParameter.java
- workflow/executor/src/main/java/com/asakusafw/workflow/executor/basic/BasicBatchExecutor.java
This PR add a command line option `--no-parameter-check` to `asakusa run` that ignores wrong batch arguments.
N/A.
This option is designed for only development or testing.
N/A.
> Add `asakusa run ... --no-parameter-check`.

- workflow/cli/src/main/java/com/asakusafw/workflow/cli/run/RunCommand.java
This PR enables `asakusa run` to recognize `-v` option, but it does nothing.
Almost commands in `asakusa` can accept `-v, --verbose` option except `asakusa run`. To pull up `-v` to a common option of `asakusa`, this enables to recognize `-v` without any effects.
N/A.
* #750
> Accept `asakusa run -v`.

- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/loader/BasicGroupLoader.java
- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/loader/BasicDataLoaderTest.java
- testing-project/asakusa-test-moderator/src/main/java/com/asakusafw/testdriver/core/PropertyType.java
This PR revises error messages of `GroupView.find()` to show the actual required type instead of internal types.
The latest implementation, when `GroupView.find()` receives inconsistent key types, it raises error messages with test-driver internal types as required types (e.g. `STRING`, `INTEGER`, ...). This PR fixes to show actual required types (e.g. `StringOption`, `IntOption`, ...) instead.
Note that, this is only `GroupView` generated by `DataLoader` in test-driver facilities.
N/A.
N/A.
> Show original type when GroupView.find() was failed.

- operation-project/directio/src/main/java/com/asakusafw/operation/tools/directio/file/AbstractFileCopyCommand.java
- operation-project/directio/src/main/java/com/asakusafw/operation/tools/directio/file/FileCopyCommand.java
- operation-project/directio/src/main/java/com/asakusafw/operation/tools/directio/file/FileGetCommand.java
- operation-project/directio/src/main/java/com/asakusafw/operation/tools/directio/file/FileGroup.java
- operation-project/directio/src/main/java/com/asakusafw/operation/tools/directio/file/FileMoveCommand.java
- operation-project/directio/src/main/java/com/asakusafw/operation/tools/directio/file/FilePutCommand.java
- operation-project/directio/src/test/java/com/asakusafw/operation/tools/directio/file/FileCopyCommandTest.java
- operation-project/directio/src/test/java/com/asakusafw/operation/tools/directio/file/FileMoveCommandTest.java
This PR adds commands `directio {copy, move}`, which enable copy/move resources on Direct I/O data sources.
`directio` command has been introduced #765, and it can copy files only between local file system and Direct I/O data sources by `put` and `get`.
Note that, `copy` accepts `--recursive` option but `move` does not. `move` originally can rename/move directories.
* #765
> Add `directio {copy,move}` commands.

- operation-project/command-portal/src/main/java/com/asakusafw/operation/tools/portal/SimpleLoggerUtil.java
- workflow/cli/src/main/java/com/asakusafw/workflow/cli/run/ExecutorLogger.java
- workflow/cli/src/main/java/com/asakusafw/workflow/cli/run/ExecutorParameter.java
- workflow/executor/src/main/java/com/asakusafw/workflow/executor/basic/BasicCommandLauncher.java
- workflow/executor/src/main/java/com/asakusafw/workflow/executor/basic/BasicCommandTaskExecutor.java
This PR enables `asakusa run -O logging` to show sub-command output messages in default.
The latest implementation, `asakusa run -O logging` has not been shown any messages in default, because the default log level of `asakusa` command is `warn` even if level of the messages is `info`.
This PR first allocate log name `com.asakusafw.cli.workflow.executor` to SLF4J logger of execution output, and then set log level of that log to `info` in default.
Note that, the default log level of `asakusa` command is still `warn`. To change the log level of execution output. Please set system property `-Dorg.slf4j.simpleLogger.log.com.asakusafw.cli.workflow.executor=...` instead of `-Dorg.slf4j.simpleLogger.defaultLogLevel=...` via environment variable `ASAKUSA_CLIENT_OPTS`.
* #784
> `asakusa run -O logging` should show messages in default.

- info/cli/src/main/java/com/asakusafw/info/cli/list/ListWindGateInputCommand.java
- info/cli/src/main/java/com/asakusafw/info/cli/list/ListWindGateOutputCommand.java
This PR fixes `asakusa list windgate *` command (without `-v`) to show simple WindGate I/O.
The latest implementation, `asakusa list windgate *` shows as same as with `-v`. This PR enables the command to show simpler style `profile-name::resource-name::resource-ID`.
N/A.
* #750
> Revise `asakusa list windgate *` without `-v`.

- info/cli/src/main/java/com/asakusafw/info/cli/list/ListOperatorCommand.java
This PR fixes `asakusa list operator` (without `-v`) to remove duplicated operators.
The latest implementation, `asakusa list operator` without `-v` sometimes shows the same operators twice or more. It because the `hashCode` operator is not consistent with `equals` method.
N/A.
N/A.
> Remove duplicated operators in `asakusa list operator`.

- gradle/build.gradle
This PR removes to check old Gradle version in `build.gradle`
This check is for compatibility with Gradle 1.x but this version is no longer supported.
N/A.
N/A.
> Remove to check old Gradle version

- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/util/hadoop/ConfigurationProvider.java
This warning log is always displayed when running TestDriver without Hadoop and related environment variables. This environment is normal use case so this warning is redundant.
N/A.
N/A.
N/A.
> Change log level when missing hadoop configuration

- operation-project/command-portal/src/main/java/com/asakusafw/operation/tools/portal/VersionCommand.java
This PR fixes `asakusa version -v` to show `hadoop` command location on `PATH` environment.
`asakusa version -v` has been show `hadoop` command location since #789, but it cannot show the command location on `PATH` environment variable.
N/A.
* #789
> Fix `hadoop` command detection in `asakusa version -v`.

- gradle/src/main/groovy/com/asakusafw/gradle/tasks/GenerateHiveDdlTask.groovy
- gradle/src/main/groovy/com/asakusafw/gradle/tasks/internal/AbstractAsakusaToolTask.groovy
- gradle/src/main/groovy/com/asakusafw/gradle/tasks/internal/AbstractTestToolTask.groovy
This PR removes use of `org.gradle.api.Nullable` which has been deprecated since the latest version of Gradle, and it replaced with `javax.annotation.Nullable`
`org.gradle.api.Nullable` has been replaced with `javax.annotation.Nullable` since Gradle `4.1` and the old one will be removed in Gradle `5.0`. This PR just removed use of them because Gradle `< 4.1` API does not provide the new one.
The `@Nullable` annotation actually does not have effect on runtime, on the one hand `@Optional` accepts `null` values for task input fields.
N/A.
N/A.
> Remove use of deprecated annotaions in Gradle plug-ins.

- operator/builtin/src/main/java/com/asakusafw/operator/builtin/DslBuilder.java
- operator/builtin/src/main/java/com/asakusafw/operator/builtin/LoggingOperatorDriver.java
- operator/builtin/src/test/java/com/asakusafw/operator/builtin/LoggingOperatorDriverTest.java
This PR fixes operator DSL compiler to make `@Logging` operator works correct.
In the latest implementation, the following `@Logging` operator's properties did not work correct:
* `@Logging` operator allows disconnected output port
* `@Logging` operator works as if is it is annotated by `@Sticky`
N/A.
N/A.
> Fix logging operator.

- operator/builtin/src/main/java/com/asakusafw/operator/builtin/ConvertOperatorDriver.java
- operator/builtin/src/test/java/com/asakusafw/operator/builtin/ConvertOperatorDriverTest.java
This PR enables to suppress `stop()` operators for `@Convert.original` outputs.
This enhancement requires that the consequent DSL compiler also supports `Connectivity` attribute for individual output ports. Please use this enhancement with asakusafw/asakusafw-compiler#177.
Note that, legacy compilers may not support this feature.
N/A.
* asakusafw/asakusafw-compiler#177
> `Convert.original` output now can leave disconnected.

- operator/builtin/src/main/java/com/asakusafw/operator/builtin/DslBuilder.java
- operator/builtin/src/main/java/com/asakusafw/operator/builtin/MasterCheckOperatorDriver.java
- operator/builtin/src/main/java/com/asakusafw/operator/builtin/MasterJoinOperatorDriver.java
- operator/builtin/src/main/java/com/asakusafw/operator/builtin/MasterJoinUpdateOperatorDriver.java
- operator/builtin/src/test/java/com/asakusafw/operator/builtin/MasterKindOperatorHelperTest.java
- operator/core/src/main/java/com/asakusafw/operator/CompileEnvironment.java
- operator/core/src/main/java/com/asakusafw/operator/flowpart/FlowPartAnnotationProcessor.java
- operator/core/src/main/java/com/asakusafw/operator/method/OperatorAnnotationProcessor.java
- operator/core/src/main/java/com/asakusafw/operator/model/OperatorDescription.java
This PR enables operators' optional output ports leave opened.
`@Master{Join,Check,JoinUpdate}.missed` output ports are now optional, so that DSL compiler will not raise errors even if these output ports would not be connected to any opposites.
This feature is disabled in default. To enable this, please insert the following in your `build.gradle`.
```
asakusafw.javac.processorOption 'com.asakusafw.operator.STRICT_OPTIONAL_OUTPUT_CONNECTIVITY', 'false'
```
Note that, this feature may not be available for legacy implementations of DSL compiler.
* #802
> Enable optional operator output ports leave opened.

- operation-project/command-portal/src/main/java/com/asakusafw/operation/tools/portal/AsakusaPortal.java
- operation-project/directio/src/main/java/com/asakusafw/operation/tools/directio/DirectIo.java
- operation-project/directio/src/main/java/com/asakusafw/operation/tools/directio/SimpleLoggerUtil.java
- utils-project/jcommander-wrapper/src/main/java/com/asakusafw/utils/jcommander/JCommanderWrapper.java
- utils-project/jcommander-wrapper/src/main/java/com/asakusafw/utils/jcommander/Messages.java
- utils-project/jcommander-wrapper/src/main/java/com/asakusafw/utils/jcommander/common/LocalPath.java
- utils-project/jcommander-wrapper/src/main/java/com/asakusafw/utils/jcommander/common/OutputParameter.java
- utils-project/jcommander-wrapper/src/main/resources/com/asakusafw/utils/jcommander/messages.properties
- utils-project/jcommander-wrapper/src/main/resources/com/asakusafw/utils/jcommander/messages_ja.properties
- utils-project/jcommander-wrapper/src/test/java/com/asakusafw/utils/jcommander/JCommanderWrapperTest.java
This PR revises error messages of `directio` command.
`directio` command sometimes provides poorer messages than `asakusa` command. This PR improves the following features.
* shared error messages about missing commands (e.g. `directio x`) with `asakusa` command, and added Japanese resource
* shared SLF4J simple logger settings with `asakusa` command, but it is enabled only if `asakusafwOrganizer.hadoop.embed` is `true`
N/A.
* #765
> Revise error messages of `directio`.

- pom.xml
This PR adds extension-less file mappings for Maven license plugin
N/A.
N/A.
N/A.
> Add extension-less file mappings for Maven license plugin

- gradle/src/main/groovy/com/asakusafw/gradle/tasks/AsakusaCompileTask.groovy
- gradle/src/main/groovy/com/asakusafw/gradle/tasks/GenerateHiveDdlTask.groovy
- gradle/src/main/groovy/com/asakusafw/gradle/tasks/RunBatchappTask.groovy
- gradle/src/main/groovy/com/asakusafw/gradle/tasks/internal/AbstractTestToolTask.groovy
This PR fixes to show warnings when using Gradle task command line option on Gradle 4.6 as follows:
```
./gradlew sparkCompileBatchapp --batch-id-prefix "moge." --warning-mode=all
org.gradle.api.internal.tasks.options.Option has been deprecated and is scheduled to be removed in Gradle 5.0. Use org.gradle.api.tasks.options.Option instead.
```
This is caused by introducing Gradle new feature that Tasks API allows custom command-line options.
See detail: https://docs.gradle.org/4.6/release-notes.html#tasks-api-allows-custom-command-line-options
Replace internal package to public one.
N/A.
> Fix warning when using Gradle task command line option on Gradle 4.6

- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/util/hadoop/ConfigurationProvider.java
This PR enables config to ignore environment hadoop configuration.
When executing TestDriver on the general Hadoop distribution environment where Hadoop client is installed with `PATH` to `hadoop` command, and that Hadoop configuration `fs.defaultFS` is for HDFS ( `hdfs://...` ) , that test fails with following logs:
```
./gradlew -i test
...
com.example.flowpart.CategorySummaryFlowPartTest > summarize FAILED
java.lang.IllegalStateException: java.io.IOException: No FileSystem for scheme: hdfs
at com.asakusafw.testdriver.FlowPartTester.runTest(FlowPartTester.java:128)
...
```
This is caused that TestDriver resolves Hadoop configuration from `PATH` of `hadoop` command but don't use the corresponding hadoop classpath.
Sometimes we would like to ignore the environment Hadoop settings, …
> Enable config to ignore environment hadoop conf

- operator/builtin/src/main/java/com/asakusafw/operator/builtin/DslBuilder.java
- operator/builtin/src/test/java/com/asakusafw/operator/builtin/ExtractOperatorDriverTest.java
- operator/builtin/src/test/java/com/asakusafw/operator/builtin/OperatorDriverTestRoot.java
- operator/builtin/src/test/resources/com/asakusafw/operator/builtin/ExtractOperatorDriverTest.files/com/example/WithEnumArgument.java.txt
- operator/core/src/main/java/com/asakusafw/operator/CompileEnvironment.java
- operator/core/src/main/java/com/asakusafw/operator/method/OperatorAnnotationProcessor.java
This enables operator methods to declare enum constant parameters.
The latest implementation, the operator compiler only had accepted primitive types and strings as extra parameters of operator methods. This PR additionally allows enum constants.
This feature is disabled in default. To enable this, please insert the following in your `build.gradle`.
```
asakusafw.javac.processorOption 'com.asakusafw.operator.ENUM_CONSTANT_PARAMETER', 'true'
```
Note that, this feature may not be available for legacy implementations of DSL compiler, and Asakusa on Spark will require extra patches.
N/A.
> Allow enum constants for operator methods.

- gradle/build.gradle
- gradle/src/main/groovy/com/asakusafw/gradle/plugins/AsakusafwBaseExtension.groovy
- gradle/src/main/groovy/com/asakusafw/gradle/plugins/AsakusafwBasePlugin.groovy
- gradle/src/main/groovy/com/asakusafw/gradle/plugins/internal/AsakusafwOrganizer.groovy
- pom.xml
This PR fix to fail on assemble task when specifing `asakusafwOrganizer.yaess.jobqueueEnabled` in `build.gradle` 
Asakusa Gradle Plugin specifies `org.apache.httpcomponents:httpcore:4.2.6` as dependencies for `YaessJobQueueLib` but that version does not exist. The correct version is `4.2.5`.
N/A.
N/A.
> Fix to assemble when enabling yaess.jobqueueEnabled

- dmdl-project/asakusa-dmdl-core/src/main/java/com/asakusafw/dmdl/analyzer/ModelDeclarationProcessor.java
- dmdl-project/asakusa-dmdl-core/src/main/java/com/asakusafw/dmdl/analyzer/PropertyDeclarationProcessor.java
- dmdl-project/asakusa-dmdl-core/src/main/java/com/asakusafw/dmdl/semantics/Declaration.java
- dmdl-project/asakusa-dmdl-core/src/main/java/com/asakusafw/dmdl/semantics/trait/ReferencesTrait.java
- dmdl-project/asakusa-dmdl-java/src/main/java/com/asakusafw/dmdl/java/emitter/driver/ProjectionDriver.java
- dmdl-project/asakusa-dmdl-java/src/test/java/com/asakusafw/dmdl/java/GeneratorTesterRoot.java
- dmdl-project/asakusa-dmdl-java/src/test/java/com/asakusafw/dmdl/java/emitter/driver/ProjectionDriverTest.java
This enables data model classes inherit deep projective models as Java interfaces, and their projective models can behave as projection of the target data model.
The latest implementation, projections must be appear in the right hand side of record model definitions.
For example, in the following DMDL snippet,  the declared model `x` composites another model `base`. and `base` has `p` as its projection. In this case, the model `x` does not have `p` as its projection even if `x` has all properties declared in `p`.
```
projective p = ...;
base = p + ...;
x = base + ...;
```
This PR enables `p` also become `x`'s projection via `base`. In other words, "`x` **inherits** all projections of `base`". 
Similarly, in the following case, `y` becomes a sub projection of `p`.
```
projective p = ...; …
```
> Inherit indirect projective models.

- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/DriverInputBase.java
- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/DriverOutputBase.java
- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/FlowDriverInput.java
- testing-project/asakusa-test-moderator/src/main/java/com/asakusafw/testdriver/core/DataModelSourceFilter.java
This PR introduces `FlowDriverInput.prepare(String, ModelTransformer)` to test facility that enables transforms test inputs.
N/A.
N/A.
N/A.
> Add `FlowDriverInput.prepare(String, ModelTransformer)`.

- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/DriverElementBase.java
- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/DriverInputBase.java
- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/FlowDriverInput.java
- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/FlowDriverOutput.java
- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/FlowDriverOutputTest.java
- testing-project/asakusa-test-moderator/src/main/java/com/asakusafw/testdriver/core/ModelTransformer.java
This PR is revision of #820, replaced `ModelTransformer` with `Consumer`.
We have introduced `prepare(String, ModelTransformer)` since #820, but the `ModelTransformer` only has functionally equivalent to `Consumer`. To gain portability, this PR replaces `ModelTransformer` with `Consumer`.
This PR additionally enables to transform test inputs from other data set kinds, for example, we introduced `transformer` parameters to Direct I/O test inputs, like `prepare(Class<? extends DataFormat<...>>, String, Consumer<...>)`.
* #820
> Use Consumer instead of ModelTransformer.

- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/TesterBase.java
- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/loader/BasicDataLoader.java
- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/loader/DataLoader.java
This PR introduces `{Batch,Jobflow,FlowPart}Tester.loader()` like `OperatorTestEnvironment.loader()`.
In #820 and #821, we have enabled to transform test input dataset. This PR additionally enables load test input datasets manually, and then can drive them to each flow input.
This PR also introduces `DataLoader.asStream()` to manipulate input dataset on the stream.
* #820 
* #821
> Introduce `*Tester.loader()`.

- testing-project/asakusa-test-driver/src/main/java/com/asakusafw/testdriver/OperatorTestEnvironment.java
- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/OperatorTestEnvironmentTest.java
- testing-project/asakusa-test-driver/src/test/java/com/asakusafw/testdriver/testing/dsl/SimpleOperatorImpl.java
This PR introduces `OperatorTestEnvironment.newInstance()` which provides operator implementation class instance from the corresponded operator class.
N/A.
N/A.
N/A.
> Introduce `OperatorTestEnvironment.newInstance()`.

- directio-project/asakusa-directio-dmdl/src/main/java/com/asakusafw/dmdl/directio/line/driver/LineFormatEmitter.java
- directio-project/asakusa-directio-dmdl/src/test/java/com/asakusafw/dmdl/directio/line/driver/LineFormatEmitterTest.java
This PR fixes Direct I/O Line support, that may crash for reading small files.
In the latest implementation, Direct I/O line does not read smaller files than the split size.
N/A.
N/A.
> Fix Direct I/O Line for small files.

- operator/builtin/src/test/java/com/asakusafw/operator/builtin/LoggingOperatorDriverTest.java
- operator/builtin/src/test/resources/com/asakusafw/operator/builtin/LoggingOperatorDriverTest.files/com/example/UnboundProjection.java.txt
- operator/core/src/main/java/com/asakusafw/operator/CompileEnvironment.java
- operator/core/src/test/java/com/asakusafw/operator/MockDataModelMirrorRepository.java
- operator/dmdl/src/main/java/com/asakusafw/operator/dmdl/DmdlDataModelMirrorRepository.java
- operator/dmdl/src/test/java/com/asakusafw/operator/dmdl/DmdlDataModelMirrorRepositoryTest.java
This PR enables operator methods to declare unbound projective models.
The latest implementation, the operator compiler rejects unbound type parameters like `public <T> void operator(T ...)`. This PR additionally allows them as "unbound projection" which means empty projection for all data models.
This feature is **enabled** in default. To disable this, please insert the following in your `build.gradle`.
```
asakusafw.javac.processorOption 'com.asakusafw.operator. UNBOUND_PROJECTION', 'false'
```
N/A.
> Enable unbound projective models.

- windgate-project/asakusa-windgate-dmdl/pom.xml
This PR fixes classpath of WindGate DMDL extensions, which has been broken since #835.
N/A.
N/A.
* #835
> fix classpath of WindGate DMDL extensions.

- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/directio/hadoop/HadoopDataSourceProfile.java
- core-project/asakusa-runtime/src/main/java/com/asakusafw/runtime/directio/util/DelimiterRangeInputStream.java
This PR enables to revert the breaking compatible change of #835.
Since #835, `FragmentableDataFormat.getMinimumFragmentSize()` **MUST** return smaller value than the required minimum fragment size.
To revert this behavior, please set the following configuration to your **Hadoop configuration (like `asakusa-resources.xml`)**:
* `com.asakusafw.directio.COMPAT835` : `true`
Note that, this commit includes a copy of `com.asakusafw.runtime.directio.util.DelimiterRangeInputStream` as deprecated class, which was moved in #835. Note that, we recommended replace that class with `com.asakusafw.runtime.io.util.LineFeedDelimitedInputStream`.
N/A.
* #835
> add backward compatible flag of #835.

- hive-project/core-stub/src/main/java/com/asakusafw/directio/hive/util/CompatibilityUtil.java
- hive-project/core-v1/src/main/java/com/asakusafw/directio/hive/orc/v1/CompatibilityV1.java
- hive-project/core-v1/src/main/java/com/asakusafw/directio/hive/parquet/v1/CompatibilityV1.java
- hive-project/core-v2/src/main/java/com/asakusafw/directio/hive/orc/v2/CompatibilityV2.java
- hive-project/core-v2/src/main/java/com/asakusafw/directio/hive/parquet/v2/CompatibilityV2.java
This PR improves how detect version detection for #834.
#834 does not work correct for Asakusa on Spark.
This commit introduces `CompatibilityUtil`, which provides installed Hive version information via `HiveVersionAnnotation`.
* #834
> better Hive version detection.

- gradle/src/main/groovy/com/asakusafw/gradle/tasks/AsakusaCompileTask.groovy
This PR fixes `asakusafw.maxHeapSize` in `*compileBatchapps` task does not work.
`asakusafw.maxHeapSize` works.
N/A.
N/A.
> Fix to work asakusafw.maxHeapSize in *compileBatchapps

- gradle/src/main/groovy/com/asakusafw/gradle/plugins/AsakusafwBasePlugin.groovy
This PR changes maven repository URL protocol from `http` to `https` in Asakusa Gradle Plugin for batch application project configurations.
This prepares Maven Central plans to stop support communication over HTTP.
* https://central.sonatype.org/articles/2019/Apr/30/http-access-to-repo1mavenorg-and-repomavenapacheorg-is-being-deprecated/
This changes to use https for Maven Central, and this changes for Asakusa Framework maven repository on S3 as well.
Also, this changes Maven Central repository URL from `repo1.maven.org/maven2` to `repo.maven.apache.org/maven2` due to the Gradle current configurations as follows:
* https://github.com/gradle/gradle/pull/3464
N/A.
> Change configure maven repository URL to use https

- .github/CONTRIBUTING.md
- README.md
- build-tools/pom.xml
- build-tools/src/main/javadoc/overview-summary.html
- gradle/build.gradle
- integration/build.gradle
- integration/src/integration-test/data/directio-tools/build.gradle
- integration/src/integration-test/data/organizer-simple/build.gradle
- integration/src/integration-test/data/sdk-eclipse/build.gradle
- integration/src/integration-test/data/sdk-simple/build.gradle
- integration/src/integration-test/data/simple/build.gradle
- integration/src/integration-test/data/windgate/build.gradle
- integration/src/integration-test/data/yaess/build.gradle
- pom.xml
- utils-project/gradle-launcher/README.md
This PR changes maven repository URL protocol from http to https in `pom.xml` and `build.gradle` for framework build configurations.
This also changes link URL to https in documentation files.
Follow-up asakusafw/asakusafw#845
The same as asakusafw/asakusafw#845
N/A.
> Change maven repository URL to use https in build configurations

- gradle/src/test/groovy/com/asakusafw/gradle/plugins/AsakusaUpgradeTest.groovy
This PR removes testcase `AsakusaUpgradeTest` -> `v1.12`.
Gradle version 1.12 (tooling API) uses HTTP protocol for dependency resolution, but Maven Central already disable HTTP and now only HTTPS enabled.
Remove this testcase.  `AsakusaUpgradeTest` -> `v1.12` is almost unnecessary at the moment, as it's for migration from a very old version (Asakusa 0.6.0).
> Remove testcase in AsakusaUpgradeTest for v1.12
